BibliothecaDAO/eternum

src/components/age.cairo, src/components/army.cairo, src/components/buildings.cairo, src/components/config.cairo, src/components/labor.cairo, src/components/metadata.cairo, src/components/owner.cairo, src/components/position.cairo, src/components/realm.cairo, src/components/resources.cairo, src/erc721/components.cairo
quick fix because dojo does not assume the traits anymore
=> fix: remove derive magic

src/systems/labor/build_labor.cairo, src/systems/labor/harvest_labor.cairo, src/systems/settling.cairo
new auth system implemented in dojo. 
in the tests spawn_test_world now needs an array of routes to give systems the necessary authorizations. 
a route is comprised of 
1. system that needs to write
2. role name
3. component it writes to
=> fix: new dojo auth system

client/README.md, client/package.json, client/src/components/cityview/RealmSwitch.tsx, client/src/components/cityview/realm/RealmInfoComponent.tsx, client/src/components/cityview/realm/RealmResourcesComponent.tsx, client/src/components/cityview/realm/trade/Market/MarketPanel.tsx, client/src/components/cityview/realm/trade/MyOffers/MyOffersPanel.tsx, client/src/containers/BaseContainer.tsx, client/src/modules/RealmManagementModule.tsx
added transitions between realms, ui polishing, added readme
=> feat: polishing, readme, transitions

contracts/src/utils.cairo, contracts/src/utils/testing.cairo
=> refactor testing.cairo

contracts/src/systems/caravan/create_caravan.cairo, contracts/src/systems/test/create_realm.cairo
PR for #86 
- update create_caravan test
=> Update create_caravan test

contracts/src/systems/caravan/create_free_transport_unit.cairo
PR for #86 
NOTE: This PR depends on #89 being merged
=> update create_free_transport_unit system test

contracts/src/components/quantity.cairo, contracts/src/systems/caravan/create_caravan.cairo, contracts/src/systems/caravan/utils.cairo, contracts/src/utils/testing.cairo
- remove `GetQuantity` system
- create `get_value` function in QuantityTrait to replace `GetQuantity` system
=> Replace GetQuantity system

contracts/src/systems/caravan/utils.cairo
PR for #86 
- update caravan utils test
=> update caravan utils test

contracts/src/systems/labor/build_labor.cairo
PR for #86 
- update build_labor system tests
=> update build_labor system tests

contracts/src/systems/labor/harvest_labor.cairo
PR for #86 
- update harvest_labor system tests
=> update harvest_labor system tests

contracts/src/systems/order/make_fungible_order.cairo
PR for #86 
- update make fungible order system test
=> update make fungible order system test

contracts/src/systems/order/attach_caravan.cairo
PR for #86 
- update attach caravan to order system test
=> update attach caravan to order system test

contracts/src/systems/order/claim_fungible_order.cairo
PR for #86 
- update claim fungible order system test
=> update claim fungible order system test

.github/workflows/test.yml, contracts/src/systems/caravan/create_free_transport_unit.cairo, contracts/src/systems/caravan/utils.cairo, contracts/src/systems/labor/build_labor.cairo, contracts/src/systems/labor/harvest_labor.cairo, contracts/src/systems/settling.cairo, contracts/src/utils/unpack.cairo
- added build to workflow
- changed workflow name to `test-contracts` for clarity
- added `[cfg(test)]` to test modules to allow `sozo build` work
=> add build workflow

client/package.json, client/src/components/NotificationsComponent.tsx, client/src/components/cityview/CityView.tsx, client/src/components/cityview/realm/RealmManagementComponent.tsx, client/src/components/cityview/realm/RealmTradeComponent.tsx, client/src/components/cityview/realm/trade/Caravans/CaravansPanel.tsx, client/src/utils/Camera.tsx
Map regions are now clickable #79
=> feat: interactive regions

contracts/src/systems/order/take_fungible_order.cairo
PR for #86 
- update take_fungible_order system test
=> update take_fungible_order system test

client/src/components/caravans/CaravanDetailsComponent.tsx, client/src/components/cityview/realm/RealmResourcesComponent.tsx, client/src/components/cityview/realm/labor/LaborBuild.tsx, client/src/components/cityview/realm/labor/LaborComponent.tsx, client/src/components/cityview/realm/labor/LaborPanel.tsx, client/src/components/cityview/realm/trade/Caravans/Caravan.tsx, client/src/components/cityview/realm/trade/Caravans/CaravansPanel.tsx, client/src/components/cityview/realm/trade/Caravans/IncomingOrder.tsx, client/src/components/cityview/realm/trade/Caravans/IncomingOrdersPanel.tsx, client/src/components/cityview/realm/trade/CreateOffer.tsx, client/src/components/cityview/realm/trade/Market/MarketOffer.tsx, client/src/components/cityview/realm/trade/Market/MarketPanel.tsx, client/src/components/cityview/realm/trade/MyOffers/MyOffer.tsx, client/src/components/cityview/realm/trade/MyOffers/MyOffersPanel.tsx, client/src/hooks/graphql/useGraphQLQueries.tsx, client/src/hooks/helpers/useCaravans.tsx, client/src/hooks/helpers/useIncomingOrders.tsx, client/src/hooks/helpers/useTrade.tsx, client/src/layouts/World.tsx
- starts syncing all of torii in browser at page start
- improved unnecessary renders
- code refactoring to allow for later filtering in realms management panel
=> feat: world sync at start + remove unnecessary renders + code refactoring 

contracts/Scarb.toml, contracts/src/components/road.cairo, contracts/src/systems/order/take_fungible_order.cairo, contracts/src/systems/road/create_road.cairo
- Pin dojo version to prevent compilation errors
- Remove custom types from road component
=> Update road component

contracts/Scarb.toml
=> unpin dojo version

client/src/components/OrdersFilterComponent.tsx, client/src/components/ResourceFilterComponent.tsx, client/src/components/cityview/realm/trade/Market/MarketOffer.tsx, client/src/components/cityview/realm/trade/Market/MarketPanel.tsx, client/src/components/cityview/realm/trade/MyOffers/MyOffersPanel.tsx, client/src/hooks/graphql/useGraphQLQueries.tsx, client/src/hooks/helpers/useCaravans.tsx, client/src/hooks/helpers/useTrade.tsx, client/src/hooks/helpers/useTradeQueries.tsx, client/src/layouts/World.tsx, client/src/utils/utils.tsx
- modified useEntityQuery from MUD to be able to filter on Order (reflexion, ...) and resource type in the trades
- added filters on orders and resource types
- added sorting 
- added the distance from maker in the market panel
=> feat: market panel add distance + distance sorting

.github/workflows/test.yml, client/src/components/cityview/realm/SettleRealmComponent.tsx, client/src/dojo/createSystemCalls.ts, contracts/Scarb.toml, contracts/src/components/resources.cairo, contracts/src/constants.cairo, contracts/src/systems/test/mint_resources.cairo, contracts/src/utils/testing.cairo
when realm is settled, 1000 of all resources are minted to him
=> feat: mint all resources in client

client/src/components/cityview/realm/trade/AcceptOffer.tsx, client/src/components/cityview/realm/trade/CreateOffer.tsx, client/src/components/worldmap/hyperstructures/FeedHyperstructure.tsx, client/src/components/worldmap/hyperstructures/HyperStructureCaravans/HyperStructureCaravan.tsx, client/src/constants/travel.ts, client/src/dojo/contractComponents.ts, client/src/hooks/graphql/useGraphQLQueries.tsx, client/src/hooks/helpers/useCaravans.tsx, client/src/utils/utils.tsx, contracts/scripts/system_components.json, contracts/src/components/position.cairo, contracts/src/systems/caravan/create_free_transport_unit.cairo
for now max donkeys = 100 per city
=> feat: return caravan home after hyperstructure + max donkeys per realm 

client/src/components/cityview/CityView.tsx, client/src/components/cityview/realm/labor/LaborPanel.tsx, client/src/components/cityview/regions/FarmsRegionTooltip.tsx, client/src/components/cityview/regions/FisheryRegionTooltip.tsx, client/src/elements/BaseRegionTooltip.tsx
New tooltips for 3d models regions
=> feat: farms & fisheries model tooltips

client/package.json, client/src/components/SignUpComponent.tsx, client/src/dojo/createOptimisticSystemCalls.ts, client/src/hooks/graphql/useGraphQLQueries.tsx, client/src/hooks/helpers/useIncomingOrders.tsx
- fix bug with remove optimisitc rendering resource update if tx not pass through
- filter out incoming orders that are not specifically on your realm position
=> fix: multiple ui fixes

client/.env.development, client/.env.production, client/src/components/cityview/realm/trade/CreateOffer.tsx, client/src/dojo/setupNetwork.ts, client/src/elements/Button.tsx, client/src/elements/RealmBadge.tsx, client/src/elements/ResourceCost.tsx, client/src/hooks/notifications/useClaimOrderNotification.tsx, client/src/hooks/notifications/useHarvestNotification.tsx, client/src/modules/scenes/MainScene.tsx
1. Added harvest button to labor notifications
2. New styling of Order Claim notifications
3. More smooth animations for Realm Switch component
4. Fixed bug with resources selection (if you select resource in "Get" section, you cant select it in "Give" section)
=> feat: harvest from notification, ui improvements

client/src/components/cityview/realm/SettleRealmComponent.tsx, client/src/components/cityview/realm/labor/LaborBuild.tsx, client/src/components/cityview/realm/labor/LaborComponent.tsx, client/src/components/worldmap/hyperstructures/HyperstructureLeaderboard.tsx, contracts/src/models/owner.cairo
- fix leaderboard sort bug
- fix owner test bug
- remove farms/fishing villages limit
=> fix some bugs

contracts/src/constants.cairo, contracts/src/models/config.cairo, contracts/src/systems/combat/contracts.cairo, contracts/src/systems/combat/interface.cairo, contracts/src/systems/combat/tests.cairo, contracts/src/systems/combat/tests/combat_attack_system_tests.cairo, contracts/src/systems/combat/tests/combat_steal_system_tests.cairo, contracts/src/systems/combat/tests/soldier_create_system_tests.cairo, contracts/src/systems/combat/tests/soldier_group_system_tests.cairo, contracts/src/systems/combat/tests/soldier_ungroup_system_tests.cairo, contracts/src/systems/config/contracts.cairo, contracts/src/systems/config/interface.cairo
- bug fixes and minor refactor
- added combat stealing tests
- rename tests
=> combat: fix bugs, update combat

client/README.md, client/src/components/SettingsComponent.tsx, client/src/layouts/World.tsx, contracts/README.md, sdk/packages/eternum/package.json
=> add in version

client/src/components/SignUpComponent.tsx, client/src/components/cityview/realm/trade/Market/MarketPanel.tsx, client/src/components/cityview/realm/trade/Market/MarketPopup.tsx
Added marketplace popup showing summary and offers list on Coins <-> Resource trades.
WIP. Need review.
=> feat: offers marketplace popup

client/src/components/NotificationsComponent.tsx, client/src/dojo/createSystemCalls.ts, client/src/hooks/notifications/useNotifications.tsx, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/index.ts
=> feat: harvest all button

client/src/components/cityview/realm/trade/Market/MarketPopup.tsx, client/src/containers/ContentContainer.tsx, client/src/elements/SecondaryPopup.tsx, client/src/layouts/World.tsx, client/src/modules/RealmManagementModule.tsx, client/src/modules/WorldMapMenuModule.tsx
1. Fixed popups dragging bug
2. Added feature to limit popups height with window height + resize handler
3. Few little fixes for marketplace popup (ui layout)
4. Sidebar transitions fix
=> fix: popups and market

contracts/src/systems/resources/contracts.cairo, contracts/src/systems/trade/contracts/trade_systems.cairo, contracts/target/dev/manifest.json, contracts/target/release/manifest.json
- fix transfer event
- remove wrong if block (always results to true)
=> fix transfer event

client/src/components/cityview/realm/RealmResourcesComponent.tsx, client/src/components/worldmap/banks/models/Bank2.tsx, client/src/layouts/World.tsx, client/src/utils/utils.tsx
Updated UI of Realm resources bar
=> feat: new resource bar UI

client/src/components/NotificationsComponent.tsx, client/src/components/cityview/realm/RealmManagementComponent.tsx, client/src/components/worldmap/hyperstructures/HyperstructureLeaderboard.tsx, client/src/dojo/createEventSubscription.ts, client/src/dojo/createUpdates.ts, client/src/elements/Button.tsx, client/src/elements/Notification.tsx, client/src/hooks/notifications/generateNotifications.tsx, client/src/hooks/notifications/useBankNotification.tsx, client/src/hooks/notifications/useCombatNotification.tsx, client/src/hooks/notifications/useHyperstructureNotification.tsx, client/src/hooks/notifications/useNotifications.tsx, client/src/hooks/notifications/utils.tsx, client/src/hooks/store/useNotificationsStore.tsx, client/src/layouts/World.tsx, client/src/utils/combat.tsx, contracts/src/systems/transport/contracts/travel_systems.cairo, contracts/target/dev/manifest.json, sdk/packages/eternum/src/constants/events.ts
new notifs for:
- caravan arrived at bank
- caravan arrived at hyperstructure
- your army has arrived at enemy
- enemy army has arrived at your realm
- enemy army is traveling to your realm
=> feat: add notifs

contracts/src/models/hyperstructure.cairo, contracts/src/systems/combat/contracts.cairo, contracts/src/systems/combat/tests/combat_steal_system_tests.cairo, contracts/src/systems/config/contracts.cairo, contracts/src/systems/config/interface.cairo, contracts/src/systems/config/tests/hyperstructure_config_tests.cairo, contracts/src/systems/labor/tests/labor_harvest_tests.cairo, contracts/src/systems/leveling/contracts.cairo, contracts/src/systems/trade/tests/trade_systems_tests/accept_order.cairo, contracts/src/systems/transport/tests/travel_systems_tests.cairo, contracts/target/dev/manifest.json
- update hyperstructure config
- allow merge and heal to hyperstructure town watch
=> update hyperstructure config

contracts/src/systems/map/contracts.cairo, contracts/target/dev/manifest.json, contracts/target/release/manifest.json
emit an event when the map is explored
=> contracts: emit event after map exploration

contracts/src/models/position.cairo
=> contracts: convert hex distance to km

client/src/components/worldmap/HexGrid.tsx, client/src/components/worldmap/armies/EnemyArmies.tsx, client/src/components/worldmap/armies/models/ArmyModel.tsx, client/src/hooks/helpers/useCombat.tsx
- Show enemy army on the world map
resolves #376
=> client: feat: show enemy army on map

client/src/components/worldmap/HexGrid.tsx, client/src/components/worldmap/armies/Armies.tsx, client/src/components/worldmap/armies/EnemyArmies.tsx, client/src/components/worldmap/armies/models/ArmyModel.tsx, client/src/components/worldmap/traveling/TravelPopup.tsx, client/src/dojo/createUpdates.ts, client/src/hooks/helpers/useCombat.tsx, client/src/hooks/helpers/useExplore.tsx, client/src/hooks/store/_mapStore.tsx
=> feat: show travel animation for ennemies and exploring

client/src/utils/Camera.tsx
- locks camera and slight code cleanup
=> camera tuning

client/src/components/HooksComponent.tsx, client/src/components/SettingsComponent.tsx, client/src/components/cityview/realm/labor/LaborBuild.tsx, client/src/components/cityview/realm/labor/LaborComponent.tsx, client/src/components/cityview/realm/trade/FastCreateOffer.tsx, client/src/containers/BlankOverlayContainer.tsx, client/src/elements/NumberInput.tsx, client/src/hooks/store/useRefreshHyperstructure.tsx, client/src/hooks/store/useUIStore.tsx, client/src/hooks/useUISound.tsx, client/src/layouts/World.tsx, client/src/utils/Camera.tsx
1. Helper hooks was extracted from top-level layout component to separate component so it does not cause rerenders of the whole component tree
2. Camera bounds have been returned, since rerender no more causing camera freeze
3. Sound effects now working
=> fix: rerender optimization, camera bounds

client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx, client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx, client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx, client/src/components/worldmap/biomes/TundraBiome.tsx
fixed seasonal forest but seems like same issue would arise in other biomes as well.
=> fix biomes

client/src/components/cityview/realm/RealmInfoComponent.tsx, client/src/components/cityview/realm/combat/defence/Defence.tsx, client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx, client/src/components/cityview/realm/combat/raids/Raid.tsx, client/src/components/cityview/realm/combat/raids/TravelRaidsPopup.tsx, client/src/components/cityview/realm/leveling/LevelingPopup.tsx, client/src/components/worldmap/HexGrid.tsx, client/src/components/worldmap/WorldMapMenuComponent.tsx
- blurred the tabs on the Eternum map with "Coming Soon"
- commented out travel to hyperstructure
- commented out conquered hyperstructure
=> feat: remove banks, hyperstructures and leaderboard

client/src/components/cityview/RealmSwitch.tsx, client/src/components/cityview/realm/labor/LaborBuild.tsx, client/src/components/cityview/realm/labor/LaborComponent.tsx, client/src/components/cityview/realm/trade/FastCreateOffer.tsx, client/src/hooks/useUISound.tsx
1. Changed build labor sound
2. Changed harvest sound (unique sound for each resource)
3. Added sounds to Create Offer resource select
4. Added fly sound when switching between realms
5. Fixed wrong sound for Wheat and Fish
=> fix: sounds update

client/src/hooks/notifications/generateNotifications.tsx, client/src/hooks/notifications/useCombatNotification.tsx
=> feat: adapt notifs to travel hex + go to army on map

client/src/components/worldmap/hexagon/HexLayers.tsx, client/src/components/worldmap/hexagon/HighlightedHexes.tsx, client/src/components/worldmap/hexagon/WorldHexagon.tsx, client/src/components/worldmap/hexagon/utils.tsx, client/src/modules/scenes/WorldMapScene.tsx
- adds fog of war
___
enhancement
___
- Refactored hexagon biome rendering logic to dynamically render different biome components based on the hexagon data.
- Optimized hexagon filtering and rendering for performance improvements.
- Updated import paths and removed unused code for cleaner and more maintainable codebase.
- Adjusted grayscale color calculation for hexagons to produce darker colors, enhancing visual contrast.
___
<tr>
<td>
<details>
<summary><strong>HexLayers.tsx</strong><dd><code>Refactor and Enhance Hexagon Biome Rendering Logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fog of war pass

client/src/components/cityview/realm/SettleRealmComponent.tsx
forgot to remove a line i added while testing
___
bug_fix
___
- Removed a hardcoded position assignment in `SettleRealmComponent`, which was likely added for testing purposes.
___
<tr>
<td>
<details>
<summary><strong>SettleRealmComponent.tsx</strong><dd><code>Remove Hardcoded Position in SettleRealmComponent</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/components/cityview/realm/SettleRealmComponent.tsx
- Removed hardcoded position assignment for `calldata[4]`.
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/445/files#diff-d13d25b362d06eaaa65834cc49970232c186a160007860b88d698b4ee1d3df …
=> fix settle hardcoded

client/map/index.html, client/realm/index.html
enhancement
___
- Enhanced the loading times of the web application by adding prefetch links to images in `client/map/index.html` and `client/realm/index.html`.
- Prefetching includes images for biomes, buildings, icons, levels, pillage, resource buildings, resources, and units.
___
<tr>
<td>
<details>
<summary><strong>index.html</strong><dd><code>Add Image Prefetching to Improve Loading Times</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/map/index.html
<li>Changed DOCTYPE declaration to uppercase.<br> <li> Added prefetch links for various images including biomes, buildings, <br>icons, …
=> fix: images prefetch

client/src/components/cityview/RealmSwitch.tsx, client/src/components/cityview/realm/RealmInfoComponent.tsx, client/src/components/cityview/realm/combat/raids/Raid.tsx, client/src/components/navigation/NavigationBubbles.tsx, client/src/elements/SecondaryPopup.tsx, client/src/hooks/store/useUIStore.tsx, client/src/hooks/useMusic.tsx, client/src/layouts/World.tsx, client/src/utils/Camera.tsx, contracts/manifests/deployments/KATANA.toml
Fixes #457 #451 #405
___
___
- Enhanced camera movement with speed parameter and immediate effect for realm views and raids.
- Added sound toggle functionality and persisted sound setting in local storage.
- Fixed z-index issue for popups to ensure proper overlay.
- Updated contract addresses and class hashes in `KATANA.toml`.
- Adjusted loading screen transition duration for smoother experience.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>RealmSwitch.tsx</strong><dd><code>Reduce Realm Transition Delay</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: camera transitions, persistent mute button, popups z-index

client/src/components/worldmap/biomes/BeachBiome.tsx, client/src/components/worldmap/biomes/DeciduousForestBiome.tsx, client/src/components/worldmap/biomes/DeepOceanBiome.tsx, client/src/components/worldmap/biomes/DesertBiome.tsx, client/src/components/worldmap/biomes/GrasslandBiome.tsx, client/src/components/worldmap/biomes/OceanBiome.tsx, client/src/components/worldmap/biomes/ScorchedBiome.tsx, client/src/components/worldmap/biomes/ShrublandBiome.tsx, client/src/components/worldmap/biomes/SnowBiome.tsx, client/src/components/worldmap/biomes/SubtropicalDesertBiome.tsx, client/src/components/worldmap/biomes/TaigaBiome.tsx, client/src/components/worldmap/biomes/TemperateDesertBiome.tsx, client/src/components/worldmap/biomes/TemperateRainforestBiome.tsx, client/src/components/worldmap/biomes/TropicalRainforestBiome.tsx, client/src/components/worldmap/biomes/TropicalSeasonalForestBiome.tsx, client/src/components/worldmap/biomes/TundraBiome.tsx
resolves #453
___
enhancement
___
- Replaced `Math.random()` with `pseudoRandom` function across various biome components to ensure seeded randomness in biome rotation.
- This change affects multiple biomes including Beach, Deciduous Forest, Deep Ocean, Desert, Grassland, Ocean, Scorched, Shrubland, Snow, Subtropical Desert, Taiga, Temperate Desert, Temperate Rainforest, Tropical Rainforest, Tropical Seasonal Forest, and Tundra.
- Ensures consistent biome rotation across sessions for a given seed, enhancing the game's deterministic behavior.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>16 files</summary><table>
<tr>
<td>
<details> …
=> fix: fixed seeded rotation biomes

client/src/components/worldmap/armies/ArmyMenu.tsx
resolves #446
___
___
- Optimized resource checks for exploration using `useMemo` and `useResources`.
- Ensured exploration only proceeds if there are sufficient food resources, enhancing the user experience by preventing actions that cannot be completed due to resource constraints.
- Updated UI elements to reflect the ability to explore based on resource availability, improving feedback to the player.
___
<tr>
<td>
<details>
<summary><strong>ArmyMenu.tsx</strong><dd><code>Enhance Exploration Feature with Resource Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix: no exploration if no food

client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
resolves #463
___
bug_fix
___
- Renamed state variable for clarity and to support both enemy and selected raiders as targets.
- Fixed an issue where `targetEntityId` was not being updated correctly when `enemyRaider` was present.
- Updated resource balance calculations to use the new `targetEntityId`, ensuring correct resource tracking.
- Added logic to determine the initial step in `StealResultPanel` based on the presence of burnt food, improving user experience.
___
<tr>
<td>
<details>
<summary><strong>AttackRaidsPopup.tsx</strong><dd><code>Generalize Target Entity Handling and Improve Initial Step Calculation</code></dd></summary>
<hr> …
=> fix: pillage screen when attacking army

client/src/components/cityview/realm/combat/raids/Raid.tsx, client/src/hooks/helpers/useRealm.tsx
solves #469
___
enhancement
___
- Introduced a new utility function `isRealmIdSettled` in `useRealm` hook to check if a realm ID is settled.
- Enhanced the Raid component to use the `isRealmIdSettled` function. This ensures that raids only consider settled realms as valid destinations.
- Utilized memoization for calculating the `destinationRealmId` based on the settlement status of the realm, improving performance.
___
<tr>
<td>
<details>
<summary><strong>Raid.tsx</strong><dd><code>Enhance Raid Component with Realm Settlement Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix: waiting on unsettled realm

client/src/components/worldmap/armies/models/WarriorModel.tsx, client/src/components/worldmap/hexagon/HexLayers.tsx, client/src/hooks/useUISound.tsx
1. Added two running sounds for units
2. Added idle warrior animation
___
enhancement
___
- Added running sound effects for warrior units and implemented logic to play these sounds based on the warrior's movement state.
- Improved the timing of sound effects during hexagon exploration.
- Introduced new hooks (`useRunningSound`) for managing running sound effects, including alternating between two sounds and fading out sounds.
___
<tr>
<td>
<details>
<summary><strong>WarriorModel.tsx</strong><dd><code>Integration of Running Sounds and Idle Animation for Warrior Model</code></dd></summary>
<hr>
client/src/components/worldmap/armies/models/WarriorModel.tsx …
=> feat: unit running sound

client/package.json, client/src/App.tsx, client/src/dojo/createSystemCalls.ts, client/src/layouts/World.tsx, pnpm-lock.yaml, sdk/packages/eternum/src/provider/index.ts
resolves #450
___
___
- Added support for displaying toast notifications using `react-toastify`.
- Implemented error handling in system calls and Eternum provider methods to display error messages as toast notifications.
- Cleaned up unused code and imports in the World component.
- Added `react-toastify` to dependencies for toast notifications.
___
<tr>
<td>
<details>
<summary><strong>App.tsx</strong><dd><code>Add Toast Notifications Support to App Component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/App.tsx
<li>Imported CSS for react-toastify.<br> <li> Added ToastContainer …
=> feat: add toast with error message if tx is reverted

client/src/components/worldmap/hexagon/HexagonGeometry.tsx, client/src/components/worldmap/hexagon/HighlightedHexes.tsx
highlight hex shape changed to hex edges
fixes #448
___
enhancement
___
- Introduced a new method `createHexagonPath` in `HexagonGeometry.tsx` to generate a path for hexagon edges, enhancing the visual representation of highlighted hexagons.
- Modified `HighlightedHexes.tsx` to use the new hexagon edge path for rendering, utilizing `THREE.TubeGeometry` for a more distinct edge visualization.
- Adjustments made to hexagon geometry rotation and material properties to better suit the new highlighting method.
___
<tr>
<td>
<details>
<summary><strong>HexagonGeometry.tsx</strong><dd><code>Add Hexagon Edge Path Creation Function</code>&nbsp; &nbsp; &nbsp; &nbsp; …
=> feat: highlight hex shape changed to hex edges

client/src/components/cityview/RealmListBoxes.tsx, client/src/components/navigation/NavigationBubbles.tsx, client/src/components/worldmap/hexagon/FixedHexagonInformation.tsx, client/src/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/containers/LeftMiddleContainer.tsx, client/src/containers/RightMiddleContainer.tsx, client/src/modules/BottomNavigation.tsx, client/src/modules/RightNavigationModule.tsx
enhancement
___
- Introduced a new component `RealmListBoxes` for managing and displaying realm selections with state management and entity querying.
- Temporarily disabled some navigation elements in `NavigationBubbles.tsx`.
- Updated styling for hexagon information display in `FixedHexagonInformation.tsx` and revised the structure of `HexagonInformationPanel.tsx`.
- Adjusted positions of `LeftMiddleContainer` and `RightMiddleContainer`.
- Enhanced bottom navigation with the addition of `RealmListBoxes`, toggle functionality for active bars, and simplified navigation buttons.
- Adjusted styling for `RightNavigationModule`.
___
<tr>
<td>
<details> …
=> add in bottom menu

contracts/src/systems.cairo, contracts/src/systems/bank.cairo, contracts/src/systems/buildings.cairo, contracts/src/systems/combat.cairo, contracts/src/systems/config.cairo, contracts/src/systems/hyperstructure.cairo, contracts/src/systems/labor.cairo, contracts/src/systems/leveling.cairo, contracts/src/systems/map.cairo, contracts/src/systems/name.cairo, contracts/src/systems/realm.cairo, contracts/src/systems/resources.cairo, contracts/src/systems/test.cairo, contracts/src/systems/trade.cairo, contracts/src/systems/transport.cairo
- nests system imports
___
enhancement
___
- Reorganized system modules into nested structures, enhancing modularity and maintainability.
- Each system module now includes contracts, interface, and tests submodules, with labor also receiving a utils submodule.
- Commented out the bank module, suggesting it may be under development or planned for future inclusion.
- Removed individual contracts, interface, and tests modules from several systems, consolidating them into the new structure.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
<td>
<details>
<summary><strong>systems.cairo</strong><dd><code>Reorganization of System Modules into Nested …
=> Cairo chore

contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_combat_contracts_combat_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_hyperstructure_contracts_hyperstructure_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_leveling_contracts_leveling_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_map_contracts_map_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_realm_contracts_realm_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_resources_contracts_resource_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_travel_systems_travel_systems.toml, contracts/src/models/config.cairo, contracts/src/models/production.cairo, contracts/src/models/resources.cairo, contracts/src/systems/buildings/contracts.cairo, contracts/src/systems/config/contracts.cairo
- bug fixes
- allow production of only reasources available on realm
___
___
- Updated contract hashes for various systems to new values.
- Enhanced tick configuration handling in `config.cairo` to better manage tick intervals.
- Improved production model logic in `production.cairo`, including better handling of end ticks and balance exhaustion.
- Updated resource model in `resources.cairo` to remove unnecessary return statement in `harvest` function.
- Added validation in `buildings/contracts.cairo` to ensure that buildings are only created on realms that produce the specified resource.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>11 …
=> contracts: production bug fixes and allow production of only resources available on realm

client/src/dojo/modelManager/ProductionManager.ts, contracts/src/models/buildings.cairo, contracts/src/models/production.cairo
fix inaccurate production depletion values bug
=> contracts: fix inaccurate production depletion values bug

client/src/dojo/modelManager/ProductionManager.ts, contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_combat_contracts_combat_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_hyperstructure_contracts_hyperstructure_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_leveling_contracts_leveling_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_map_contracts_map_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_realm_contracts_realm_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_resources_contracts_resource_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_test_contracts_resource_test_resource_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_trade_contracts_trade_systems_trade_systems.toml, contracts/manifests/dev/base/contracts/eternum_systems_transport_contracts_road_systems_road_systems.toml, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml, contracts/src/models/buildings.cairo
- client: ensure resource balance is never less than 0
- contracts: fix building nearby bonuses
___
___
- Fixed balance calculation in `ProductionManager.ts` to prevent negative values.
- Added logging for productions of a specific resource type in `ProductionManager.ts`.
- Updated class hashes in TOML and JSON manifests for various contracts to reflect new versions.
- Enhanced building production logic in `buildings.cairo` for better bonus calculation and fixed parameter naming inconsistency.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug_fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ProductionManager.ts</strong><dd><code>Fix Balance Calculation and Add …
=> production bug fixes

client/src/ui/components/worldmap/Compass.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx
If it makes sense to add, here's a compass
closes #455
=> Add compass to worldmap

client/src/ui/components/worldmap/Compass.tsx, client/src/ui/utils/Camera.tsx
fixes #611 
___
___
- Enhanced the compass rotation logic in `Compass.tsx` to determine the shortest rotation path and apply it, improving the responsiveness and accuracy of the compass UI.
- Fixed the compass letters rotation to correctly counter the compass direction, ensuring they remain upright relative to the viewer.
- Integrated camera position and target updates with the UI store in `Camera.tsx`, allowing for better state management and reactivity in the application's UI.
___
<tr>
<td>
<details>
<summary><strong>Compass.tsx</strong><dd><code>Enhance Compass Rotation Logic and UI Update</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Update compass on rotation

client/src/ui/components/construction/BuildArea.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/elements/BaseThreeTooltip.tsx
Added UI layout for costs in construction menu and in hexception 3d view in build mode.
Not connected to actual values
___
enhancement
___
- Added a new component `BuildingCostThree` to display costs associated with each building type in a tooltip within the building preview.
- Enhanced the building selection interface by integrating cost display tooltips, improving user interaction with cost information.
- Updated `BaseThreeTooltip` component to accept a `distanceFactor` prop, allowing for customizable tooltip distance, and improved the tooltip's visual styling for better clarity.
___
<tr>
<td>
<details> …
=> feat: costs UI

client/src/hooks/helpers/useArmies.tsx, client/src/hooks/store/_mapStore.tsx, client/src/hooks/store/useUIStore.tsx, client/src/types/index.ts, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/military/ArmyPanel.tsx, client/src/ui/components/models/armies/WarriorModel.tsx, client/src/ui/components/worldmap/HoveringContainer.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx, client/src/ui/components/worldmap/hexagon/FixedHexagonInformation.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx, client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx, client/src/ui/modules/entity-details/EntityDetails.tsx, client/src/ui/modules/military/Military.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx
enhancement
___
- Introduced new types `ClickedHex` and `HighlightPosition` to standardize and clarify data structures across components.
- Refactored map store and UI store to utilize these new types, enhancing code maintainability and type safety.
- Updated several components to adapt to these new types, ensuring consistent data handling and function calls.
- Removed redundant color handling in `useUIStore`, simplifying the store's responsibilities.
___
</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>_mapStore.tsx</strong><dd><code>Refactor and Enhance Map Store with New Types and Highlight Handling</code></dd></summary>
<hr> …
=> selected hex highlight + HoveringContainer

client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/GroundGrid.tsx
Fixed #636 
also changed water color for fishery model
___
bug_fix
___
- Fixed the hexagon geometry by adding a smaller hexagon as a hole to the larger hexagon in `GroundGrid.tsx`.
- Updated the water color for buildings of type `FishingVillage` in `ExistingBuildings.tsx` to match the biome color.
___
<tr>
<td>
<details>
<summary><strong>ExistingBuildings.tsx</strong><dd><code>Update Water Color for Fishing Village Buildings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/construction/ExistingBuildings.tsx
<li>Import <code>biomes</code> from <code>@bibliothecadao/eternum</code>.<br> <li> …
=> fix: hexagon hole, water color

client/src/dojo/createClientComponents.ts, client/src/hooks/helpers/useBuildings.tsx
solves #618
___
enhancement
___
- Added optimistic rendering for building placement and destruction in `useBuildings` hook.
- Introduced UUIDs for managing unique override identifiers during optimistic updates.
- Enhanced `createClientComponents` to support component overrides, improving UI responsiveness.
___
<tr>
<td>
<details>
<summary><strong>createClientComponents.ts</strong><dd><code>Add Optimistic Component Override in Client Components</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/dojo/createClientComponents.ts
<li>Added optimistic component override for <code>Building</code> in <br><code>createClientComponents</code>.<br>
</details> …
=> Optimistic building

client/src/ui/components/trading/Marketplace.tsx
enhancement
___
- Added a new feature to cancel trade orders in the marketplace component.
- Integrated system call for cancelling orders and handling the return of resources.
- Implemented a loading state to manage UI during the cancellation process.
- Removed unused components related to trade offers, streamlining the codebase.
___
<tr>
<td>
<details>
<summary><strong>Marketplace.tsx</strong><dd><code>Add Trade Cancellation Feature to Marketplace</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/trading/Marketplace.tsx
<li>Removed unused imports: …
=> solves #629 by adding cancel trade

contracts/src/models/buildings.cairo, contracts/src/models/resources.cairo
New building quantity model
___
enhancement
___
- Introduced `BuildingQuantity` struct to manage building counts more efficiently.
- Replaced the use of `QuantityTracker` with `BuildingQuantity` in building and resource management.
- Simplified the logic for updating building counts during production processes.
- Updated resource balance calculations to use the new `BuildingQuantity` model.
___
<tr>
<td>
<details>
<summary><strong>buildings.cairo</strong><dd><code>Implement BuildingQuantity Model for Building Management</code>&nbsp; </dd></summary>
<hr>
contracts/src/models/buildings.cairo
<li>Introduced a new struct <code>BuildingQuantity</code> to …
=> add new building quantity model

client/src/ui/components/construction/ExistingBuildings.tsx
=> fix: animations

contracts/scripts/set_config.sh
Enhancement
___
- Updated `DONKEY_SPEED` to 300 seconds per kilometer, equating to 12 km/hour, enhancing the speed configuration.
- Introduced a new environment variable `ARMY_SPEED`, set to the same value as `DONKEY_SPEED` for consistency across different modes.
- Modified the speed configuration commands to use the new `ARMY_SPEED` variable, ensuring both donkeys and army entities have the same speed settings.
___
<tr>
<td>
<details>
<summary><strong>set_config.sh</strong><dd><code>Update Speed Settings for Donkeys and Army</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
=> speed up donkeys

contracts/Scarb.lock, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml, contracts/scripts/contracts.sh, contracts/scripts/set_admin_bank.sh, contracts/src/systems/dev/contracts.cairo, contracts/src/systems/dev/contracts/bank.cairo
- new file set_admin_bank.sh:
-  creates a bank at location x: 2147483901 and y: 2147483803 which is a non realm, non ocean location on the middle of the map.
-  the script calls set_admin_bank which is a dev function only callable by the admin and allows to set a tile as explored and set a bank on it.
-  the script mints resources for the admin and then calls add_liquidity to add resources on the pools. 
- the pool sizes are dependant on the starting mint amounts for the realm (10x each starting amount)
- 200 lords are added in each pool. Ex: for donkeys. since there are 30 donkeys per realm at first, it's adding 300 donkeys and 200 lords to the donkey pool of the admin bank.
- all amounts are set at the beginning of the file and can be changed.
- the script has a 2 second delay between …
=> add admin bank with liquidity

client/src/hooks/store/useLeaderBoardStore.tsx, client/src/ui/components/worldmap/leaderboard/LeaderboardPanel.tsx, client/src/ui/components/worldmap/leaderboard/OrdersLeaderboard.tsx, client/src/ui/components/worldmap/leaderboard/PlayersLeaderboard.tsx, client/src/ui/modules/leaderboard/LeaderBoard.tsx
leaderboard counting the number of shards per player and per order.
Will only show realms/orders that have at least 1 shard
___
enhancement
___
- Refactored leaderboard logic to focus on tracking resources instead of lords.
- Updated UI components to display resource-related information, including player and order stats.
- Added resource icons and names to the leaderboard panels for better user experience.
- Enhanced data handling to support resource IDs and improved sorting and filtering based on resource amounts.
___
<tr>
<td>
<details>
<summary><strong>useLeaderBoardStore.tsx</strong><dd><code>Refactor Leaderboard Logic to Track Resources</code>&nbsp; …
=> ethershards leaderboard

client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/worldmap/BannerFlag.tsx
Animated banner added to the Castle in Hexception View. #612
For now the banner image is the same for all players, but can be easily replaced with uniqute textures based on stored tokenId
https://github.com/BibliothecaDAO/eternum/assets/4090500/3fc7b472-6fb6-4468-a3a5-c2e0dcb9cc4a
___
enhancement
___
- Added a new `BannerFlag` component to animate flags in the game environment.
- Integrated the `BannerFlag` component into the `ExistingBuildings` component, positioning it dynamically.
- The animation of the flag is achieved by manipulating vertex positions over time to simulate waving.
___
<tr>
<td>
<details> …
=> feat: animated flag

contracts/scripts/set_config.sh, contracts/scripts/system_models.json, contracts/src/systems/combat/contracts.cairo
___
- Reduced `DONKEY_CAPACITY` and introduced `ARMY_CAPACITY` in the shell script, adding a new command for setting army capacity.
- Added "Weight" to the system models in JSON configuration.
- Enhanced the pillaging logic in the Cairo contract to handle multiple resource types and improved the conditions for resource transfer.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>set_config.sh</strong><dd><code>Adjust Army and Donkey Capacity Settings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
contracts/scripts/set_config.sh …
=> pillage bug fixes

client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/list/EntityList.tsx
- When buying troops / updating entities, changes are seen immediately
- Improved the hovering logic on buildings when destroying
___
___
- Enhanced the hover logic in `ExistingBuildings.tsx` to improve user interaction by enabling hover only when not in destroy mode and adjusting conditional rendering based on the mode.
- Increased tooltip distance in `ExistingBuildings.tsx` to enhance visibility.
- Updated `EntityList.tsx` to fix an issue where the entity panel did not refresh with the latest entity data, improving data consistency.
___
<tr>
<td>
<details>
<summary><strong>ExistingBuildings.tsx</strong><dd><code>Enhance Hover Logic …
=> Small improvements

contracts/src/systems/combat/contracts.cairo, contracts/src/systems/map/contracts.cairo, contracts/src/systems/resources/contracts.cairo, contracts/src/systems/trade/contracts/trade_systems.cairo, contracts/src/systems/transport/contracts/donkey_systems.cairo
remove pillaged resource from structure balance when structure is pillaged
___
___
- Enhanced resource transfer logic across multiple systems (combat, map, resources, trade) to include parameters for resource burning and ownership enforcement.
- Simplified donkey creation in transport systems by removing redundant checks and directly passing necessary parameters.
- Refactored resource management to better handle resource transfers, including adjustments based on ownership and resource burning.
___
<tr>
<td>
<details>
<summary><strong>contracts.cairo</strong><dd><code>Enhance Resource Transfer Handling in Combat Systems</code>&nbsp; …
=> pillage bug fix

contracts/scripts/system_models.json, contracts/src/models/buildings.cairo, contracts/src/models/position.cairo, contracts/src/systems/combat/contracts.cairo
___
- Added new model entries "Building", "Population", "BuildingQuantityv2" to system_models.json to support new features.
- Introduced a new method `center` in Building model to standardize building center coordinates.
- Enhanced Direction and Coord models with better display formatting.
- Implemented a detailed mechanism in combat systems to destroy buildings during pillage, including direction-based destruction logic.
___
<tr>
<td>
<details>
<summary><strong>system_models.json</strong><dd><code>Add new model entries to system_models.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> destroy building during pillage

client/src/hooks/helpers/useExplore.tsx, client/src/hooks/helpers/useHexPosition.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/GroundGrid.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/components/military/Battle.tsx, client/src/ui/components/resources/ResourceWeight.tsx, client/src/ui/components/worldmap/armies/Armies.tsx, client/src/ui/components/worldmap/hexagon/FixedHexagonInformation.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx, client/src/ui/layouts/World.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/onboarding/Steps.tsx, client/src/ui/utils/Camera.tsx
___
- Enhanced various components by refactoring state access to use direct property access, improving performance and readability.
- Introduced `isComponentMounted` ref in multiple components to manage subscriptions and state updates more effectively during the component lifecycle.
- Removed unnecessary console logs and unused components to clean up the codebase.
___
</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td>
<details>
<summary><strong>useExplore.tsx</strong><dd><code>Enhance resource subscription management and cleanup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/hooks/helpers/useExplore.tsx
<li>Added …
=> Performance

client/src/ui/components/construction/SelectPreviewBuilding.tsx
resolves #706
___
enhancement
___
- Enhanced resource production display in `SelectPreviewBuilding.tsx` to include dynamic icons and detailed production information per cycle.
- Updated section headings for costs to be more descriptive and clear.
- Improved error messaging for insufficient resources during building, enhancing user feedback.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Enhance Building Information Display and Clarity</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/construction/SelectPreviewBuilding.tsx
<li>Enhanced the display of …
=> better building info

client/src/ui/modules/transactions/Transactions.tsx
enhancement
___
- Improved error message handling in transaction failures by extracting the relevant part using regex.
- Enhanced UI feedback for failed transactions by changing the text style to red, larger, and bold.
___
<tr>
<td>
<details>
<summary><strong>Transactions.tsx</strong><dd><code>Enhance Error Message Display and Extraction in Transactions</code></dd></summary>
<hr>
client/src/ui/modules/transactions/Transactions.tsx
<li>Extracted error message using regex from transaction failure data.<br> <li> Displayed the extracted error message in a more prominent style.<br> <li> Added logging for the extracted error message.<br>
</details>
</td> …
=> only show relevant part of failed tx error msg

client/src/hooks/helpers/useRealm.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/hints/HintBox.tsx, client/src/ui/components/models/buildings/worldmap/Castles.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/components/worldmap/hexagon/SelectWorldMapBuilding.tsx, client/src/ui/modules/assistant/Assistant.tsx, client/src/ui/modules/banking/Banks.tsx, client/src/ui/modules/construction/Construction.tsx, client/src/ui/modules/entity-details/EntityDetails.tsx, client/src/ui/modules/events/Events.tsx, client/src/ui/modules/hyperstructures/Hyperstructures.tsx, client/src/ui/modules/leaderboard/LeaderBoard.tsx, client/src/ui/modules/military/Military.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/questing/Questing.tsx, client/src/ui/modules/resources/Resources.tsx, client/src/ui/modules/settings/Settings.tsx, client/src/ui/modules/trade/Trading.tsx
solves #721
___
___
- Optimized various components by refactoring state access to use direct selectors from `useUIStore`, reducing unnecessary re-renders.
- Removed unused states and imports to simplify components and improve performance.
- Added a new `TickProgress` component to handle the display of progress in a cycle, enhancing UI responsiveness.
___
</strong></td><td><details><summary>21 files</summary><table>
<tr>
<td>
<details>
<summary><strong>useRealm.tsx</strong><dd><code>Optimize useGetRealms Hook to Reduce Rerenders</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Fix rerenders

client/src/dojo/createSystemCalls.ts, client/src/hooks/helpers/useExplore.tsx, client/src/hooks/helpers/useRealm.tsx, client/src/hooks/helpers/useTravel.tsx, client/src/ui/components/models/armies/WarriorModel.tsx, client/src/ui/components/worldmap/armies/Armies.tsx, client/src/ui/components/worldmap/armies/Army.tsx, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml, contracts/src/systems/transport/contracts/travel_systems.cairo, sdk/packages/eternum/src/constants/resources.ts
=> fixed repeated animation bug
=> fixed wrong direction army model bug
___
___
- Enhanced animation handling in `useExplore` and `useTravel` hooks to prevent repeated animations and added error handling.
- Refactored `WarriorModel` and `Army` components for better clarity and efficiency.
- Updated game configuration to change the tick interval to 1 second.
- Updated contract class hashes in manifest files for consistency.
___
<tr>
<td>
<details>
<summary><strong>useExplore.tsx</strong><dd><code>Enhance Animation Handling in useExplore Hook</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Fix animation

client/src/ui/components/models/buildings/worldmap/Castles.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx, client/src/ui/components/worldmap/armies/ArmyMenu.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/elements/Button.tsx, config/index.ts, sdk/packages/eternum/src/constants/resources.ts
___
- Simplified the `ArmyMenu` component by removing the `entityId` prop and related network provider.
- Updated styling in `ArmyInfoLabel` for better visual consistency.
- Enhanced `ArmyMenu` with new button functionalities for 'Attack' and 'Travel' and simplified resource handling.
- Exported `useEventHandlers` function in `HexLayers.tsx` for external use.
- Improved `Button` component's `onClick` handling to support event parameter and added conditional checks.
- Increased the carry capacity for 'army' in Eternum constants to support larger loads.
___
<tr>
<td>
<details>
<summary><strong>Army.tsx</strong><dd><code>Simplify …
=> Construction polish

sdk/packages/eternum/src/config/index.ts
enhancement
___
- Enhanced the precision of capacity configurations for `donkey` and `army` by incorporating `resourcePrecision` in the weight calculations.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Enhance Capacity Configuration Precision</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
sdk/packages/eternum/src/config/index.ts
<li>Updated the weight calculation for <code>donkey</code> and <code>army</code> in <br><code>setCapacityConfig</code> by multiplying with <code>resourcePrecision</code>.<br>
</details>
</td>
<td><a …
=> fix config capacity

client/src/hooks/helpers/useHexPosition.tsx, client/src/hooks/store/useUIStore.tsx, client/src/ui/components/construction/BigHexBiome.tsx, client/src/ui/components/construction/BuildArea.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/GroundGrid.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/modules/scenes/HexceptionViewScene.tsx, client/src/ui/utils/utils.tsx, sdk/packages/eternum/src/constants/hex.ts
1. Fixed #697 
2. Fixed #659
3. Hexception center switched from 4,4 to 10,10
4. Reimplemented generateHexPositions in more clear way
5. Fixed different mismatches with coordinates and offsets in worldmap and hexception view
___
___
- Refactored hex position calculations across multiple components to use a centralized utility function `getNeighborHexes`.
- Updated camera position and target settings in `useUIStore`.
- Adjusted hardcoded hex positions in `ExistingBuildings` and other components to a new central position (10,10).
- Enhanced hex position generation logic in `GroundGrid` and `BigHexBiome` for dynamic calculation.
- Modified hex data processing in `HexLayers` to adjust for row parity.
___
<table><thead><tr><th></th><th align="left">Relevant …
=> fix: coordinates mismatch

client/src/ui/components/cityview/realm/trade/FastCreateOffer.tsx, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml, contracts/scripts/testing/mint_resource.sh, contracts/src/systems/trade/contracts/trade_systems.cairo, contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo
Closes #740
___
___
- Enhanced the 'Create Offer' button in the UI to be disabled if the resource amount to give or get is zero, preventing invalid trade offers.
- Updated the mint resource script to handle command-line arguments and different modes, improving usability and flexibility.
- Updated class hashes in the development manifest files for consistency and correct references.
- Added checks in the trade systems contract to prevent trade orders with zero resource amounts, addressing potential bugs.
- Introduced tests to ensure that trade orders with zero resource amounts are correctly handled, increasing the robustness of the system.
___ …
=> feat: Client + contracts: disallow user to create offer if amount of resource is 0

client/src/ui/modules/scenes/HexceptionViewScene.tsx
solves #754
___
enhancement
___
- Refactored `HexceptionViewScene` to improve code readability and maintainability:
- Consolidated individual position constants into a single `positions` object for cleaner and more manageable code.
- Removed several unused imports and variables to tidy up the codebase.
- Utilized a map function to dynamically render `BigHexBiome` components based on the new `positions` object, enhancing the flexibility and scalability of the rendering logic.
- Streamlined conditional rendering logic for `neighborHexesInsideView` to ensure components are rendered only when necessary.
___
<tr>
<td>
<details> …
=> fix refresh bug + small refactor

client/src/dojo/modelManager/ProductionManager.ts, client/src/ui/components/resources/ResourceChip.tsx
goal is to show that a resource is being consumed without producing anything
related to #739
=> show useless consumption

client/src/ui/components/list/EntityList.tsx, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/elements/Button.tsx, client/src/ui/elements/SecondaryPopup.tsx, client/src/ui/elements/TextInput.tsx, client/src/ui/modules/onboarding/Steps.tsx
___
- Updated various UI components to enhance visual consistency and functionality:
- Changed hover background color in `EntityList` for better visual feedback.
- Simplified HTML structure in `ArmyList` and adjusted layout for better spacing.
- Major refactor in `ArmyManagementCard` to improve troop and travel management interfaces.
- Updated button styles across multiple components for a consistent look and feel.
- Modified text input and popup styles to align with the new UI theme.
- These changes aim to provide a more cohesive and user-friendly interface.
___
<tr>
<td>
<details> …
=> miltary management

client/src/ui/components/construction/BuildArea.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/list/EntityList.tsx, client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx, client/src/ui/components/worldmap/armies/ArmyMenu.tsx, client/src/ui/elements/BaseThreeTooltip.tsx, client/src/ui/elements/DojoHtml.tsx, client/src/ui/modules/scenes/HexceptionViewScene.tsx, sdk/packages/eternum/src/constants/resources.ts
- adds button to destroy building
- building info popup doesn't come on hover anymore but on click
- scaled exploration costs by the multiplier
___
___
- Added a destroy button to buildings, allowing users to remove buildings directly from the UI.
- Changed building interaction from hover to click-triggered, enhancing user experience by preventing accidental triggers.
- Introduced additional buttons support in the BuildingInfo component, enabling the inclusion of custom actions like the destroy button.
- Improved key handling in EntityList to ensure unique keys by using index.
- Replaced Html with DojoHtml in several components for consistency and better integration with the Dojo context.
- Enhanced the BaseThreeTooltip component with positioning options to allow more …
=> feat: destroy building button + scale exploration costs

client/src/dojo/modelManager/ProductionManager.ts, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/hints/HintBox.tsx, client/src/ui/components/resources/ResourceChip.tsx, client/src/ui/elements/BaseThreeTooltip.tsx, client/src/ui/elements/Button.tsx, client/src/ui/elements/CircleButton.tsx, client/src/ui/elements/TextInput.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/onboarding/Steps.tsx, client/src/ui/utils/utils.tsx, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml
- adds depleation time
- general styles
___
___
- Added a new method `timeUntilValueReached` in `ProductionManager.ts` to calculate the time until a resource balance reaches a specified value.
- Updated UI components to enhance visual elements and integrate the new method for displaying resource depletion times.
- Modified button styles, particularly the "danger" variant, to improve UI distinction and aesthetics.
- Updated contract class hashes in the manifest files, reflecting changes in the underlying smart contracts.
___
<tr>
<td>
<details>
<summary><strong>ProductionManager.ts</strong><dd><code>Add method to calculate depletion …
=> add in time till depleation

contracts/src/systems.cairo, contracts/src/systems/config/tests/hyperstructure_config_tests.cairo, contracts/src/systems/hyperstructure/contracts.cairo, contracts/src/systems/hyperstructure/interface.cairo, contracts/src/systems/leveling/contracts.cairo, contracts/src/systems/leveling/interface.cairo, contracts/src/systems/leveling/tests/internal_leveling_tests.cairo, contracts/src/systems/leveling/tests/realm_leveling_tests.cairo, contracts/src/systems/map/tests.cairo, contracts/src/systems/realm/tests.cairo, contracts/src/systems/resources/tests/resource_approval_system_tests.cairo, contracts/src/systems/resources/tests/resource_transfer_system_tests.cairo, contracts/src/systems/trade/tests/trade_systems_tests/accept_order.cairo, contracts/src/systems/trade/tests/trade_systems_tests/cancel_order.cairo, contracts/src/systems/trade/tests/trade_systems_tests/create_order.cairo, contracts/src/systems/transport/tests/road_systems_tests.cairo, contracts/src/systems/transport/tests/travel_systems_tests.cairo
Fixes interface importing in tests.
Removed deprecated tests (Trade chests, Inventory, Trade refactor)
Closes #671
=> Fix tests interface

client/src/hooks/helpers/useStructures.tsx, client/src/hooks/store/_buildModeStore.tsx, client/src/ui/components/construction/GroundGrid.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/models/buildings/worldmap/Structures.tsx, client/src/ui/components/structures/construction/StructureConstructionMenu.tsx, client/src/ui/components/structures/construction/StructurePreview.tsx, client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx, sdk/packages/eternum/src/utils/index.ts
=> create list of structures and their positions
=> show structure preview in red if conditions are not met:
- no structures
- explored
- not ocean
=> fix bugs
___
___
- Updated `createHyperstructure` function parameter type from `number` to `bigint`.
- Enhanced `setPreviewBuilding` to support `StructureType`.
- Added type assertion for `previewBuilding` in `handlePlacement`.
- Updated building images path and menu exclusions for `Settlement` and `Hyperstructure`.
- Refactored structure models and fetching logic.
- Added new structure types to `STRUCTURE_IMAGE_PATHS` and updated filtering logic.
- Enhanced structure preview and placement validation.
- Cleaned up and updated coordinate calculation logic in `HexLayers`.
- Removed commented-out code and unused imports in …
=> Structures models

client/src/hooks/helpers/useStructures.tsx, client/src/ui/components/military/Battle.tsx, client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/ui/components/worldmap/realms/RealmListItem.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx
enhancement, other
___
- Enhanced the `useStructures` hook to handle and format structures at a given position.
- Updated the `Battle` component to display structures using the new `StructureListItem` component.
- Cleaned up the `HexagonInformationPanel` and `RealmListItem` components by removing commented-out code.
- Added a new `StructureListItem` component for displaying structure information.
___
<tr>
<td>
<details>
<summary><strong>useStructures.tsx</strong><dd><code>Enhance structure handling in `useStructures` hook.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/hooks/helpers/useStructures.tsx
<li>Added …
=> add structure info in EntityDetails

client/src/ui/components/construction/BigHexBiome.tsx, client/src/ui/components/construction/BuildArea.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/modules/scenes/HexceptionViewScene.tsx
enhancement, bug fix
___
- Added a `flat` parameter to the `generateHexPositions` and `BigHexBiome` functions to handle flat biomes more effectively.
- Refactored the `ExistingBuildings` component by extracting middle building logic into a new `MiddleBuilding` component.
- Cleaned up unused imports and variables across multiple files.
- Updated the `HexceptionViewScene` to use the new `MiddleBuilding` component and improved conditional rendering logic.
___
<tr>
<td>
<details>
<summary><strong>BigHexBiome.tsx</strong><dd><code>Add flat parameter to BigHexBiome component and refactor logic</code></dd></summary>
<hr> …
=> fix biomes + middle building

client/src/ui/components/worldmap/hexagon/HexLayers.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx
1. Remove hex highlight on mouse out
2. Deselect selected hex on repeat click
3. Open/close left and right sidebars on mouse enter/out
___
___
- Added `mouseOutHandler` to handle hexagon mouse out events in `HexLayers.tsx`.
- Updated `clickHandler` to deselect hexagon on repeat click in `HexLayers.tsx`.
- Integrated `mouseOutHandler` in the hexagon group event handlers in `HexLayers.tsx`.
- Improved left navigation menu UX by adding debounce to delay closing and implementing `onPointerEnter` and `onPointerLeave` handlers in `LeftNavigationModule.tsx`.
- Improved right navigation menu UX by adding debounce to delay closing and implementing `onPointerEnter` and `onPointerLeave` handlers in `RightNavigationModule.tsx`.
___
<table><thead><tr><th></th><th …
=> feat: small ux improvements

client/src/dojo/createUpdates.ts, client/src/hooks/helpers/useHexPosition.tsx, client/src/hooks/store/_mapStore.tsx, client/src/hooks/store/useLeaderBoardStore.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/hyperstructures/HyperstructurePanel.tsx, client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx, client/src/ui/components/models/buildings/worldmap/Structures.tsx, client/src/ui/elements/NumberInput.tsx, client/src/ui/modules/hyperstructures/Hyperstructures.tsx, sdk/packages/eternum/src/constants/buildings.ts, sdk/packages/eternum/src/utils/index.ts
- Add model of half done when in hexception 
- UI of hyperstructures contributions 
- show everyone's % shares of hyperstructure when done
___
Enhancement, Tests
___
- Added support for tracking and displaying finished and unfinished hyperstructures.
- Enhanced UI components to show detailed progress and shares for hyperstructures.
- Refactored leaderboard computation logic for better modularity and clarity.
- Updated building models and destruction logic to handle new hyperstructure states.
- Adjusted layout and styles for various UI components.
___
</strong></td><td><details><summary>11 files</summary><table>
<tr>
<td>
<details> …
=> feat: various features

client/src/hooks/store/_mapStore.tsx
Bug fix
___
- Replaced `useState` with `useRef` for `subCreated` to ensure the subscription state is maintained across renders.
- Added a cleanup function to unsubscribe from the observable when the component unmounts, preventing potential memory leaks.
- Renamed the `subscription` variable to `sub` for better clarity and consistency.
___
<tr>
<td>
<details>
<summary><strong>_mapStore.tsx</strong><dd><code>Fix subscription handling and cleanup in map store hook.</code>&nbsp; </dd></summary>
<hr>
client/src/hooks/store/_mapStore.tsx
<li>Replaced <code>useState</code> with <code>useRef</code> for <code>subCreated</code> to maintain subscription <br>state …
=> fix subscription

client/src/ui/components/construction/GroundGrid.tsx, client/src/ui/components/models/buildings/worldmap/Structures.tsx, client/src/ui/modules/scenes/WorldMapScene.tsx
___
- Updated placeholder geometry in `GroundGrid` component to fix a shape bug.
- Enhanced lighting in `Structures` component by adding `useHelper`, adjusting light power, and replacing `pointLight` with `spotLight`.
- Improved directional light handling in `WorldMapScene` by adding a target reference and updating light position logic.
___
<tr>
<td>
<details>
<summary><strong>GroundGrid.tsx</strong><dd><code>Update placeholder geometry in GroundGrid component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/construction/GroundGrid.tsx
<li>Changed placeholder geometry from …
=> [client] lights update

client/src/ui/components/ModalContainer.tsx, client/src/ui/components/construction/GroundGrid.tsx, client/src/ui/components/hints/HintBox.tsx, client/src/ui/components/models/armies/WarriorModel.tsx, client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx, client/src/ui/layouts/World.tsx, client/src/ui/modules/onboarding/Steps.tsx
1. Spelling improvement: Claim All (looks weird since there's single button) -> Claim Rewards
2. Close Trading modal with Esc button #862
3. Fixed loading screen stuck after page reload
4. Added warrior model highlight on hover
5. Console log error #871
6. Building UX #873
___
___
- Enabled closing modal with 'Escape' key and adjusted button padding.
- Adjusted building placement order to prevent issues.
- Improved button text for claiming rewards.
- Added hover effect to warrior model and cleaned up code.
- Improved event subscription and UI path handling.
- Added redirect to home on loading screen.
- Improved styling for account selection step.
___ …
=> [client] UX fixes and improvements

client/src/hooks/helpers/useGuilds.tsx, client/src/ui/elements/StaminaResourceCost.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx, client/src/ui/utils/utils.tsx
Closes #877
___
___
- Added a null check for `guild.entity_id` in the `formatGuilds` function to prevent potential crashes.
- Fixed the stamina cost calculation in the `StaminaResourceCost` component by negating the travel and explore costs.
- Refactored the `BottomNavigation` component to use the `isRealmSelected` function from `utils`, simplifying the code and improving reusability.
- Moved the `isRealmSelected` function to the `utils` module for better code organization and reuse.
___
<tr>
<td>
<details>
<summary><strong>useGuilds.tsx</strong><dd><code>Add null check for guild entity ID in formatGuilds</code>&nbsp; &nbsp; &nbsp; …
=> Fix stamina on explore

client/src/ui/containers/BottomMiddleContainer.tsx, client/src/ui/elements/CircleButton.tsx
Closes #876
___
Bug fix
___
- Refactored the `CircleButton` component to ensure proper layering of children and background elements.
- Moved children elements inside the button tag in `CircleButton`.
- Adjusted styles for background image and notification badge in `CircleButton`.
- Minor formatting fix in `BottomMiddleContainer` component.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
<tr>
<td>
<details>
<summary><strong>BottomMiddleContainer.tsx</strong><dd><code>Minor formatting fix in BottomMiddleContainer component.</code>&nbsp; </dd></summary>
<hr>
client/src/ui/containers/BottomMiddleContainer.tsx
<li>Removed an extra space in the className attribute of the div element.<br>
</details>
</td> …
=> Fixes quest number behind container

contracts/src/models/buildings.cairo, contracts/src/models/level.cairo, contracts/src/models/resources.cairo, contracts/src/models/road.cairo, contracts/src/systems/combat/contracts.cairo, contracts/src/systems/map/tests.cairo, contracts/src/systems/resources/contracts.cairo, contracts/src/systems/transport/contracts/donkey_systems.cairo, contracts/src/systems/transport/contracts/travel_systems.cairo
should resolve #897 
but there are still warnings from external libs
___
Bug fix
___
- Replaced class names with `Self` in method calls across multiple files to fix internal compiler warnings.
- Improved code readability by reformatting function parameters and struct initializations.
- Reordered imports in test files for better organization.
___
</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>buildings.cairo</strong><dd><code>Fix internal compiler warnings by using `Self` in method calls.</code></dd></summary>
<hr>
contracts/src/models/buildings.cairo
<li>Replaced <code>BuildingQuantityv2TrackerImpl</code> with <code>Self</code> for …
=> contracts: fix internal compiler warnings

client/src/hooks/helpers/useBuildings.tsx
#848 Fix
___
Bug fix
___
- Added an optional `resourceType` parameter to the `optimisticBuilding` function to allow for more flexible building creation.
- Updated the `optimisticBuilding` function to use the provided `resourceType` or default to 0 if not provided.
- Modified the call to `optimisticBuilding` to include the `resourceType` parameter, ensuring consistency and correctness in building creation.
___
<tr>
<td>
<details>
<summary><strong>useBuildings.tsx</strong><dd><code>Add optional <code>resourceType</code> parameter to <code>optimisticBuilding</code> function</code></dd></summary>
<hr>
client/src/hooks/helpers/useBuildings.tsx
<li>Added an …
=> fix: optimistic building of mines #848

.github/workflows/test.yml
enhancement
___
- Updated the Dojo version in the CI workflow from v0.6.1-alpha.4 to v0.7.0-alpha.5.
___
<tr>
<td>
<details>
<summary><strong>test.yml</strong><dd><code>Update Dojo version in CI workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/test.yml
<li>Updated the Dojo version in the CI workflow from v0.6.1-alpha.4 to <br>v0.7.0-alpha.5.<br>
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/905/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798c …
=> Update dojo version in CI

.github/workflows/test.yml, contracts/manifests/dev/manifest.json, contracts/manifests/dev/manifest.toml, contracts/src/systems/combat/contracts.cairo, contracts/src/systems/map/tests.cairo
battle: allow claim when army is dead and not in battle
___
___
- Added a health check before asserting the battle state in the `claim_structure` function to ensure the army is alive.
- Updated transaction hash, block number, and class hashes in `manifest.json` and `manifest.toml` for contract addresses.
- Reformatted parameters in the `army_create` function for better readability.
- Added output type to the `army_is_protector` function in the manifest.
___
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update contract metadata and function outputs.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Battle claim fix

client/src/hooks/helpers/useQuests.tsx, client/src/ui/components/hints/HintBox.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx
- Disable quests popup when none left
- Show quests 1 by 1 in order, instead of all at once
- Closes quests popup on  claim (unsure about how this feels)
Closes #895 
Closes #900
___
___
- Enhanced quest tracking by adding `HasClaimedStartingResources` component.
- Updated quest completion logic to check for claimed resources.
- Simplified quest steps and prizes structure.
- Updated HintBox component to handle claimed quests and toggle popup.
- Improved quest button state handling in BottomNavigation component.
___
<tr>
<td>
<details>
<summary><strong>useQuests.tsx</strong><dd><code>Enhance quest tracking and completion …
=> Enh quests popup

client/src/ui/components/trading/MarketModal.tsx, client/src/ui/components/trading/MarketOrderPanel.tsx
___
- Added `overflow-y-auto` class to the main container in `MarketModal` to handle vertical overflow.
- Wrapped resource trait in a `div` with `truncate` class in `MarketOrderPanel` for text overflow handling.
- Adjusted grid layout for `OrderRowHeader` and `OrderRow` components.
- Added error handling and loading state management for order acceptance in `MarketOrderPanel`.
- Improved UI for order rows and buttons in `MarketOrderPanel`.
___
<tr>
<td>
<details>
<summary><strong>MarketModal.tsx</strong><dd><code>Add vertical overflow handling to MarketModal component.</code>&nbsp; </dd></summary>
<hr> …
=> Fix trades y overflow + adjust trades header & rows grid

client/src/dojo/createClientComponents.ts, client/src/hooks/helpers/useExplore.tsx, client/src/hooks/helpers/useTravel.tsx
___
- Added `Stamina` component to the list of overridable components.
- Simplified the `explore` function by removing the `finally` block and adjusted error handling.
- Introduced `optimisticTravelHex` for handling optimistic updates in travel and integrated it into `travelToHex`.
- Improved error handling in `travelToHex` to revert position overrides and update animation paths correctly.
___
<tr>
<td>
<details>
<summary><strong>createClientComponents.ts</strong><dd><code>Add Stamina component to client components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix optimistic travel/explore

client/src/dojo/createClientComponents.ts, client/src/hooks/helpers/useExplore.tsx, client/src/hooks/helpers/useTravel.tsx, client/src/ui/components/HooksComponent.tsx, client/src/ui/components/worldmap/armies/Armies.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx, client/src/ui/components/worldmap/hexagon/useTravelPath.tsx
=> force the position to be the correct one when no animation
=> remove unncessary rerenders
=> Fix optimistic travel

client/src/ui/components/military/EntitiesArmyTable.tsx, client/src/ui/elements/CircleButton.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx
Closes #914 
___
- Fixed key prop for `ArmyChip` component in `EntitiesArmyTable`.
- Added `notificationLocation` prop to `CircleButton` component and implemented dynamic notification positioning.
- Set `notificationLocation` prop for `CircleButton` in `BottomNavigation` and `RightNavigationModule`.
- Added imports for `useEntityArmies` and `useStamina` in `LeftNavigationModule`.
- Filtered armies with stamina left and set `notification` and `notificationLocation` props for `CircleButton` in `LeftNavigationModule`.
___
<tr>
<td>
<details>
<summary><strong>EntitiesArmyTable.tsx</strong><dd><code>Fix key props in EntitiesArmyTable …
=> Fixes notification position + adds armies with moves left notification

client/src/hooks/helpers/useResources.tsx, client/src/ui/components/entities/Entity.tsx, client/src/ui/components/resources/DepositResources.tsx
Closes #903
___
___
- Refactored `useGetOwnedEntityOnPosition` to `useOwnedEntitiesOnPosition` in `useResources.tsx`.
- Added helper functions `getOwnedEntitiesOnPosition` and `getOwnedEntityOnPosition` for better modularity.
- Updated `Entity.tsx` to use the new helper functions for determining entity state and deposit entity ID.
- Modified the display logic for entity states `Idle` and `WaitingToOffload` based on the presence of resources and deposit entity ID.
- Ensured `DepositResources` component is conditionally rendered based on the entity state in `Entity.tsx`.
- Replaced old entity ownership retrieval logic with the new helper functions in `DepositResources.tsx`.
___
<table><thead><tr><th></th><th align="left">Relevant …
=> Changed 'waiting to offload' only when at base

client/src/hooks/helpers/useExplore.tsx, client/src/hooks/helpers/useStamina.tsx, client/src/hooks/helpers/useTravel.tsx
Enhancement
___
- Integrated `optimisticStaminaUpdate` function into `useExplore` and `useTravel` hooks to handle stamina updates optimistically.
- Refactored `getStamina` function in `useStamina` to use `currentArmiesTick` directly.
- Added error handling to remove `Position` and `Stamina` overrides if the operation fails.
___
<tr>
<td>
<details>
<summary><strong>useExplore.tsx</strong><dd><code>Integrate optimistic stamina update in exploration logic.</code></dd></summary>
<hr>
client/src/hooks/helpers/useExplore.tsx
<li>Imported <code>EternumGlobalConfig</code> and <code>useStamina</code>.<br> <li> Added <code>optimisticStaminaUpdate</code> call in …
=> Optimistic stamina

contracts/src/systems/map/tests.cairo, contracts/src/systems/realm/tests.cairo
This should enable CI tests again
___
Bug fix, Tests
___
- Reformatted the `army_create` function signature in `contracts.cairo` for better readability.
- Enhanced the setup function in `map/tests.cairo` by deploying `realm_systems_dispatcher` and setting initial resources.
- Added a new test `test_mint_starting_resources_twice` in `realm/tests.cairo` to ensure starting resources cannot be minted twice.
- Removed redundant test `test_map_explore__ensure_explorer_cant_hex_travel_till_next_tick` in `map/tests.cairo`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting
<tr>
<td>
<details>
<summary><strong>contracts.cairo</strong><dd><code>Reformat `army_create` function signature.</code>&nbsp; &nbsp; …
=> Fix map+realm tests, fixes CI tests

client/src/shaders/placeholderMaterial.tsx, client/src/ui/components/construction/BuildArea.tsx, client/src/ui/components/models/armies/WarriorModel.tsx, client/src/ui/components/models/buildings/worldmap/InstancedCastles.tsx, client/src/ui/components/models/buildings/worldmap/ShardsMines.tsx, client/src/ui/components/models/buildings/worldmap/Structures.tsx, client/src/ui/components/structures/construction/StructurePreview.tsx, client/src/ui/components/worldmap/Flags.jsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/hexagon/HoveredHexagon.tsx, client/src/ui/components/worldmap/hexagon/UnitHighlight.tsx, client/src/ui/modules/scenes/MainScene.tsx
1. Fixed freeze bug wen new realm is settled
2. Updated highlight colors, changed bloom effect setting
3. Fixed bug with transparency overlap
___
___
- Fixed a bug with render order causing transparency issues.
- Enhanced color settings and effects across multiple components.
- Updated bloom effect settings for improved visual quality.
- Increased opacity for various UI elements to improve visibility.
- Refactored flag rendering logic for better performance and maintainability.
___
</strong></td><td><details><summary>11 files</summary><table>
<tr>
<td>
<details>
<summary><strong>placeholderMaterial.tsx</strong><dd><code>Update placeholder material color …
=> [client] crash fix, colors update

client/src/ui/components/trading/MarketModal.tsx, client/src/ui/components/trading/TransferBetweenEntities.tsx
closes #983
___
enhancement
___
- Added a console log statement in `MarketModal.tsx` to output `otherRealms` data for debugging purposes.
- Enhanced the layout in `TransferBetweenEntities.tsx` by adding `overflow-auto` and `overflow-y-scroll` classes to div elements for better content handling.
- Adjusted button size from `md` to `xs` in `TransferBetweenEntities.tsx` for a more compact UI.
___
<tr>
<td>
<details>
<summary><strong>MarketModal.tsx</strong><dd><code>Add console log for debugging `otherRealms` data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/trading/MarketModal.tsx
- …
=> add fixed h

client/src/ui/components/trading/MarketModal.tsx, client/src/ui/components/trading/MarketOrderPanel.tsx
- style UX updates
___
Enhancement
___
- Enhanced the market resource sidebar by adding a `Qty` column and excluding `Lords` from filtered resources.
- Introduced a `depth` calculation for market resources to display the number of offers.
- Updated the `MarketOrderPanel` to include a `depth` property in the `MarketResource` component.
- Improved the styling and layout of market orders and order rows.
- Added logic to determine if an order can be accepted based on available balance.
___
<tr>
<td>
<details>
<summary><strong>MarketModal.tsx</strong><dd><code>Enhance market resource sidebar with quantity and depth</code>&nbsp; &nbsp; </dd></summary>
<hr> …
=> Loaf market

client/.env.production, client/src/ui/components/entities/Entity.tsx, client/src/ui/layouts/World.tsx, config/index.ts, sdk/packages/eternum/src/constants/global.ts
___
- Refactored entity state and resource rendering logic in `Entity.tsx` for better readability and maintainability.
- Extracted version display logic into a separate `VersionDisplay` component in `World.tsx`.
- Commented out unused configuration setup calls in `config/index.ts`.
- Updated donkey speed configuration value in `global.ts`.
- Added `VITE_PUBLIC_GAME_VERSION` environment variable in `.env.production`.
___
<tr>
<td>
<details>
<summary><strong>Entity.tsx</strong><dd><code>Refactor and improve entity state and resource rendering</code>&nbsp; </dd></summary>
<hr>
client/src/ui/components/entities/Entity.tsx
<li>Refactored …
=> smol fixes and improvements

client/src/dojo/createSystemCalls.ts, client/src/hooks/helpers/useResources.tsx, client/src/ui/components/entities/Entity.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx
- improvements all around
___
___
- Added `PromiseQueue` class to manage promise queueing and introduced `withQueueing` and `withErrorHandling` wrappers for system calls.
- Refactored `getArrivalsWithResources` and `getAllArrivalsWithResources` to use `useMemo` for optimization.
- Simplified entity status rendering logic and updated background color logic based on entity state.
- Fixed notification count for resource arrivals and updated `AllResourceArrivals` component usage.
___
<tr>
<td>
<details>
<summary><strong>createSystemCalls.ts</strong><dd><code>Add promise queueing and error handling to system calls</code>&nbsp; &nbsp; …
=> improve transport management

client/src/index.css, client/src/ui/layouts/World.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleDetails.tsx, client/src/ui/modules/military/battle-view/BattleProgressBar.tsx, client/src/ui/modules/military/battle-view/BattleSideView.tsx, client/src/ui/modules/military/battle-view/EntityAvatar.tsx, client/src/ui/modules/military/battle-view/LockedResources.tsx, client/src/ui/modules/military/battle-view/TopScreenView.tsx, client/src/ui/modules/military/battle-view/Troops.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/TopLeftNavigation.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/tailwind.config.js
- overall battle styles
___
Enhancement
___
- Added new CSS class `.clip-squared-top` in `tailwind.config.js`.
- Repositioned `TopLeftContainer` in `World` layout.
- Added toggle button and updated styles in `Battle`.
- Updated button styles and images in `BattleActions`.
- Simplified CSS classes in `BattleDetails`.
- Refactored gradient logic and updated styles in `BattleProgressBar`.
- Updated layout and added `EntityAvatar` in `BattleSideView`.
- Added address prop and updated image logic in `EntityAvatar`.
- Updated layout and styles in `LockedResources`.
- Added ornate borders to `TopScreenView`.
- Updated styles in `Troops`.
- Removed `SettingsWindow` from `LeftNavigationModule`.
- Added `SettingsWindow` to `TopLeftNavigation`.
- Updated styles in `TopMiddleNavigation`.
- Added new …
=> combat styles

config/index.ts
enhancement
___
- Uncommented multiple configuration setup function calls in `config/index.ts`.
- Ensured all configuration functions are now active, which includes production, building category population, population, building, resource building, weight, combat, capacity, speed, quest, globals, hyperstructure, and stamina configurations.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Uncomment configuration setup function calls</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
config/index.ts
<li>Uncommented multiple configuration setup function calls.<br> <li> …
=> fix: uncomment configs

client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/containers/BottomMiddleContainer.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx
Closes #996
___
enhancement
___
- Enhanced the `HoverBuilding` component to display ongoing costs for resource buildings using the `ResourceInfo` component.
- Extended the `ResourceInfo` component to support additional buttons.
- Prevented pointer events on `BottomMiddleContainer` to avoid interaction issues.
- Enabled pointer events on `BottomNavigation` for better user interaction.
___
<tr>
<td>
<details>
<summary><strong>ExistingBuildings.tsx</strong><dd><code>Enhance building tooltip to show ongoing costs for resource buildings.</code></dd></summary>
<hr>
client/src/ui/components/construction/ExistingBuildings.tsx
<li>Added import for …
=> feat: Add ongoing costs to clicked buildings

client/src/ui/components/trading/MarketOrderPanel.tsx
- checks
___
___
- Updated the `canAccept` logic to include a check for `enoughDonkeys` to ensure that orders can only be accepted if there are enough donkeys available.
- Added a visual indicator (a pulsing red icon) to show when there are not enough donkeys to accept an order.
- Removed redundant code that previously handled the donkey check separately.
___
<tr>
<td>
<details>
<summary><strong>MarketOrderPanel.tsx</strong><dd><code>Fix and enhance donkey check in MarketOrderPanel</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/trading/MarketOrderPanel.tsx
<li>Moved …
=> fix donkeys check

client/src/hooks/helpers/useEntities.tsx, client/src/ui/components/hints/Combat.tsx, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/military/ArmyViewCard.tsx, client/src/ui/components/models/buildings/worldmap/Battles.tsx, client/src/ui/components/resources/InventoryResources.tsx, client/src/ui/components/trading/MarketOrderPanel.tsx, client/src/ui/components/worldmap/realms/RealmListItem.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx, client/src/ui/containers/BattleContainer.tsx, client/src/ui/elements/Button.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleDetails.tsx, client/src/ui/modules/military/battle-view/BattleSideView.tsx, client/src/ui/modules/military/battle-view/BattleView.tsx, client/src/ui/modules/military/battle-view/EntityAvatar.tsx, client/src/ui/modules/military/battle-view/LockedResources.tsx, client/src/ui/modules/military/battle-view/Troops.tsx
- Fixes some visual bugs in BattleView + problem with a claim
___
enhancement, bug fix
___
- Fixed import order and adjusted indentation in `useEntities.tsx`.
- Updated battle label logic to include `selectedEntity` in `Battles.tsx`.
- Adjusted button size and height in `MarketOrderPanel.tsx`.
- Fixed button styles and loading spinner alignment in `Button.tsx`.
- Changed button text from "Close" to "Overview" and adjusted battle view height in `Battle.tsx`.
- Added ownership check for claim logic and disabled raid button if `structure.isMine` in `BattleActions.tsx`.
- Adjusted layout and spacing in `BattleDetails.tsx`.
- Improved layout and alignment in `BattleSideView.tsx`.
- Ensured minimum width for avatar image and added margin in `EntityAvatar.tsx`.
- Updated layout and alignment in …
=> feat: Combat documentation + small style issues + claim logic fix

client/src/hooks/helpers/useGuilds.tsx, client/src/ui/components/worldmap/guilds/GuildMembers.tsx, client/src/ui/components/worldmap/guilds/Guilds.tsx, client/src/ui/components/worldmap/guilds/MyGuild.tsx, client/src/ui/elements/SelectBox.tsx
- some minor styles and a bug fix around perms
___
___
- Added `getGuildOwner` function in `useGuilds` hook to fetch the owner of a guild.
- Integrated guild owner logic in `GuildMembers` component to conditionally render UI elements based on ownership.
- Updated CSS classes and layout for `Guilds`, `MyGuild`, and `SelectBox` components to improve styling and user experience.
___
<tr>
<td>
<details>
<summary><strong>useGuilds.tsx</strong><dd><code>Add function to fetch guild owner in useGuilds hook</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/hooks/helpers/useGuilds.tsx
<li>Added …
=> guild work

contracts/src/models/bank/bank.cairo, contracts/src/models/combat.cairo, contracts/src/systems/bank/contracts.cairo, contracts/src/systems/bank/contracts/bank.cairo, contracts/src/systems/bank/contracts/liquidity.cairo, contracts/src/systems/bank/contracts/liquidity_systems.cairo, contracts/src/systems/bank/contracts/swap.cairo, contracts/src/systems/bank/tests/bank.cairo, contracts/src/systems/bank/tests/liquidity.cairo, contracts/src/systems/bank/tests/swap.cairo, contracts/src/systems/dev/contracts/bank.cairo
1. add LP: instant
2. remove LP: 2x travel time because you need to pickup resources since you don't have donkeys at the bank (need to pickup)
3. swap: instant in AMM, 2x travel time to for realm to get resources since you don't have donkeys at the bank (need to pickup)
also changed bank_systems, swap_systems, liquidity_systems to just bank, swap, liquidity
___
Enhancement, Tests
___
- Removed the `BankAccounts` struct from the bank model.
- Reformatted comments and updated mock functions in the combat model.
- Renamed modules from `bank_systems`, `liquidity_systems`, and `swap_systems` to `bank`, `liquidity`, and `swap`.
- Removed `open_account` function and added `pickup_resources_from_bank` function in the bank contract.
- Updated liquidity functions to include `entity_id` and modified …
=> [contracts] Instant AMM

client/hex/index.html, client/index.html, client/map/index.html, client/src/dojo/modelManager/BattleManager.ts, client/src/hooks/helpers/useEntities.tsx, client/src/hooks/helpers/useRealm.tsx, client/src/ui/components/construction/ExistingBuildings.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleProgressBar.tsx, client/src/ui/modules/military/battle-view/BattleSideView.tsx, client/src/ui/modules/military/battle-view/BattleView.tsx, client/src/ui/modules/military/battle-view/EntityAvatar.tsx, client/src/ui/modules/military/battle-view/LockedResources.tsx
___
- Refactored BattleManager to include troop updates and damage calculations.
- Updated address name decoding in useRealm hook.
- Added user armies in battle prop to Battle and BattleView components.
- Added army selection dropdown and updated action handlers in BattleActions.
- Added battle status message and simplified health display in BattleProgressBar.
- Clear selection after joining a battle in BattleSideView.
- Adjusted styling for EntityAvatar component.
- Fixed incorrect resource retrieval and added overflow handling in LockedResources.
___
</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td>
<details> …
=> feat: Add button for army selection + style fixes

client/src/ui/components/hyperstructures/StructureCard.tsx, client/src/ui/components/military/Battle.tsx, client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/ui/components/worldmap/realms/RealmListItem.tsx
Enhancement
___
- Refactored and enhanced the `StructureCard` component and its related components (`MergeTroopsPanel` and `TroopExchange`), improving layout and styling.
- Made minor styling adjustments to the `EnemyArmies` component.
- Updated the layout and styling of the `HexagonInformationPanel`, including commenting out the `Coordinates` component.
- Enhanced the layout and styling of the `RealmListItem` component, improving the display of resources and inventory.
___
<tr>
<td>
<details>
<summary><strong>StructureCard.tsx</strong><dd><code>Refactor and enhance StructureCard and related components.</code></dd></summary>
<hr> …
=> feat: Styling of hex information panel

client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx, config/bank/index.ts
enhancement
___
- Added the `Banks` component back to the WorldMap JSX structure in `WorldHexagon.tsx`.
- Adjusted the X coordinate for the bank model in `index.ts`.
___
<tr>
<td>
<details>
<summary><strong>WorldHexagon.tsx</strong><dd><code>Add Banks component to WorldMap JSX structure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx
<li>Imported <code>Banks</code> from the appropriate module.<br> <li> Added <code>Banks</code> component to the JSX structure of <code>WorldMap</code>.<br>
</details>
</td>
<td><a …
=> add bank model back on world map + change coords

client/src/hooks/helpers/useArmies.tsx, client/src/ui/components/hyperstructures/StructureCard.tsx, client/src/ui/components/military/Battle.tsx, client/src/ui/components/resources/InventoryResources.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/armies/CombatLabel.tsx, client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/ui/components/worldmap/realms/RealmListItem.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleDetails.tsx, client/src/ui/modules/military/battle-view/BattleProgressBar.tsx, client/src/ui/modules/military/battle-view/BattleView.tsx, client/src/ui/modules/military/battle-view/EntityAvatar.tsx, client/src/ui/modules/military/battle-view/LockedResources.tsx, client/src/ui/modules/military/battle-view/Troops.tsx
___
- Exported utility functions `checkIfArmyLostAFinishedBattle` and `checkIfArmyAlive` in `useArmies.tsx`.
- Refactored and enhanced multiple UI components for better layout and readability.
- Added state management and toggle functionality for resource visibility in `InventoryResources` and `RealmListItem`.
- Updated battle-related components to improve user experience and functionality.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>16 files</summary><table>
<tr>
<td>
<details>
<summary><strong>useArmies.tsx</strong><dd><code>Export utility functions for army status checks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
=> feat: battle visual and qol

client/src/dojo/createSystemCalls.ts, client/src/ui/components/hints/HintBox.tsx, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/provider.ts
creates multicall to avoid one tx going through but not the other
___
Enhancement
___
- Added `mint_resources_and_claim_quest` function in `createSystemCalls` to handle minting resources and claiming quests in a single call.
- Updated `HintBox` component to use the new `mint_resources_and_claim_quest` function instead of separate calls.
- Introduced `mint_resources_and_claim_quest` method in `EternumProvider` class.
- Defined `MintResourcesAndClaimProps` interface for the combined operation properties.
___
<tr>
<td>
<details>
<summary><strong>createSystemCalls.ts</strong><dd><code>Add mint_resources_and_claim_quest function for combined …
=> mint resources and claim quest in 1 multicall

client/src/dojo/modelManager/MarketManager.ts, client/src/hooks/helpers/useTravel.tsx, client/src/ui/components/bank/AddLiquidity.tsx, client/src/ui/components/bank/BankList.tsx, client/src/ui/components/bank/ConfirmationPopup.tsx, client/src/ui/components/bank/LiquidityResourceRow.tsx, client/src/ui/components/bank/LiquidityTable.tsx, client/src/ui/components/bank/ResourceBar.tsx, client/src/ui/components/bank/Swap.tsx, client/src/ui/components/cityview/realm/trade/AcceptOffer.tsx, client/src/ui/components/resources/ResourceWeight.tsx, client/src/ui/components/trading/MarketOrderPanel.tsx, client/src/ui/components/trading/Marketplace.tsx, client/src/ui/components/trading/TransferBetweenEntities.tsx, sdk/packages/eternum/src/constants/global.ts
only client work
=> fixes #1063 #1062 #1061 #1050
=> Fix amm ux

client/src/dojo/modelManager/BattleManager.ts, client/src/hooks/helpers/useArmies.tsx, client/src/hooks/helpers/useBattles.tsx, client/src/hooks/helpers/useHyperstructures.tsx, client/src/hooks/helpers/useResources.tsx, client/src/hooks/store/useLeaderBoardStore.tsx, client/src/hooks/store/useQuestStore.tsx, client/src/ui/components/entities/Entity.tsx, client/src/ui/components/hyperstructures/HyperstructurePanel.tsx, client/src/ui/components/hyperstructures/HyperstructureResourceChip.tsx, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/military/BattlesArmyTable.tsx, client/src/ui/components/military/EntitiesArmyTable.tsx, client/src/ui/components/models/buildings/worldmap/Battles.tsx, client/src/ui/components/trading/ResourceArrivals.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleView.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx, contracts/scripts/testing/mint_resource.sh
- fixes armies appearing in the arrivals list even though they're dead 
- add possibility to leave a battle with a defending army that lost, this unlocks a realm from a state where it's in a lost battle so it can't transfer and also can't leave because the battle is lost so it doesn't show up on the map
- fixes points calculations and points layout in hyperstructure panel
___
___
- Fixed armies appearing in the arrivals list even though they're dead.
- Added possibility to leave a battle with a defending army that lost.
- Fixed points calculations and points layout in hyperstructure panel.
- Improved army filtering and renamed hook to `useArmiesByEntityOwner`.
- Enhanced battle information retrieval and filtering.
- Fixed resource cost calculation in hyperstructures. …
=> fix: army deposits battle bugs + hyperstructure points calculations

client/src/dojo/createSystemCalls.ts, client/src/hooks/helpers/useArmies.tsx, client/src/hooks/helpers/useBattles.tsx, client/src/hooks/helpers/useResources.tsx, client/src/hooks/helpers/useStructures.tsx, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/entities/Entity.tsx, client/src/ui/components/hints/Buildings.tsx, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/military/Battle.tsx, client/src/ui/components/worldmap/armies/Army.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleView.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx, sdk/packages/eternum/src/constants/global.ts, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/provider.ts
___
- Fixed incorrect function calls and props in battle-related functions.
- Renamed functions for better clarity and consistency.
- Updated conditions to check for army presence.
- Adjusted resource output calculations.
- Reorganized imports for better readability.
- Updated reward resources and amounts in global configuration.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details>
<summary><strong>createSystemCalls.ts</strong><dd><code>Fix incorrect function call in battle leave and raid</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/dojo/createSystemCalls.ts
- Fixed function call to …
=> Fix: transfer to structures not working because of OwnerEntity on position query

client/src/ui/components/worldmap/armies/ArmyHitBox.tsx, client/src/ui/components/worldmap/armies/ArmyInfoLabel.tsx, client/src/ui/modules/navigation/BottomNavigation.tsx
removed the army info hovering on top of the armies because it's decreasing the performance
___
___
- Removed `showAllArmies` state and related logic from `ArmyHitBox` to improve performance.
- Simplified visibility logic for `ArmyInfoLabel` in `ArmyHitBox`.
- Fixed type casting for `nextBlockTimestamp` in `ArmyInfoLabel`.
- Removed `nextBlockTimestamp` and `showAllArmies` state and related logic from `BottomNavigation`.
- Removed unused CircleButton for showing all armies in `BottomNavigation`.
___
<tr>
<td>
<details>
<summary><strong>ArmyHitBox.tsx</strong><dd><code>Remove army hover performance impact by simplifying label …
=> remove all army labels

client/src/ui/components/bank/LiquidityResourceRow.tsx, client/src/ui/components/bank/LiquidityTable.tsx
Closes #1098
___
Enhancement
___
- Refactored `LiquidityResourceRow` component to use a grid layout instead of a table row, improving the alignment and display of resources and liquidity amounts.
- Updated `LiquidityTable` component to replace the table layout with a grid layout, enhancing the overall structure and readability of the liquidity information.
___
<tr>
<td>
<details>
<summary><strong>LiquidityResourceRow.tsx</strong><dd><code>Refactor LiquidityResourceRow to use grid layout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/bank/LiquidityResourceRow.tsx
<li>Changed table row to a …
=> Fix table grid

client/src/ui/components/quest/QuestList.tsx
Closes #1157
___
___
- Removed the `useQuests` import as it was unused.
- Introduced a new filter `unclaimedQuests` to check for quests that are not claimed.
- Updated the "Skip Tutorial" button to only display if there are unclaimed quests.
- Modified the `SkipTutorial` component to accept `setSkipTutorial` and `unclaimedQuests` as props.
- Ensured the `SkipTutorial` component resets the `skipTutorial` state upon completion.
___
<tr>
<td>
<details>
<summary><strong>QuestList.tsx</strong><dd><code>Conditional display of "Skip Tutorial" button based on unclaimed </code><br><code>quests</code></dd></summary>
<hr> …
=> Remove skip tutorial button once done w/ quests

client/src/hooks/helpers/useStamina.tsx, client/src/ui/containers/BlankOverlayContainer.tsx, client/src/ui/layouts/World.tsx
___
- Added null checks in `useStamina.tsx` to prevent potential errors when accessing stamina configurations.
- Modified `BlankOverlayContainer` to ensure it detects click events by adding `pointer-events-auto`.
- Reordered imports in `World.tsx` for better readability and cleaned up class names.
___
<tr>
<td>
<details>
<summary><strong>useStamina.tsx</strong><dd><code>Add null checks for stamina configurations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/hooks/helpers/useStamina.tsx
<li>Added null checks for <code>knightConfig</code>, …
=> fix: modals not detecting click events

client/src/three/components/ArmyManager.ts, client/src/three/components/BattleManager.ts, client/src/three/scenes/Worldmap.ts, client/src/three/systems/SystemManager.ts, client/src/three/systems/types.ts, client/src/ui/containers/BattleContainer.tsx, contracts/src/constants.cairo
___
- Introduced `BattleManager` class to handle battle updates and integrated it into `WorldmapScene`.
- Added `BattleSystemUpdate` type and handling in `SystemManager`.
- Enabled pointer events for `BattleContainer` to fix interaction issues.
- Removed unused `BuildingTypes` enum from constants.
- Reorganized imports and improved code readability in several files.
___
<tr>
<td>
<details>
<summary><strong>ArmyManager.ts</strong><dd><code>Refactor imports and improve code readability</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/components/ArmyManager.ts …
=> feat: display battles on worldmap

client/src/ui/components/worldmap/armies/ActionInfo.tsx, client/src/ui/containers/BaseContainer.tsx, client/src/ui/containers/BlankOverlayContainer.tsx, client/src/ui/elements/CircleButton.tsx, client/src/ui/elements/SecondaryPopup.tsx, client/src/ui/elements/Tooltip.tsx, client/src/ui/layouts/World.tsx, client/src/ui/modules/LoadingScreen.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleProgressBar.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/onboarding/Steps.tsx
enhancement
___
- Reordered imports across multiple files for better organization.
- Removed redundant `backdrop-blur-2xl` and similar classes from various components to optimize performance.
- Simplified background image handling in `CircleButton` component and added conditional class for active state.
- Removed unused variables and notifications in `LeftNavigationModule`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ActionInfo.tsx</strong><dd><code>Reorder imports for better organization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> enh: Optimize react

client/src/three/scenes/Worldmap.ts, contracts/manifests/dev/deployment/manifest.json, contracts/manifests/dev/deployment/manifest.toml
Bug fix, Configuration changes
___
- Fixed the condition logic for scaling hexagons in `Worldmap.ts` to correctly handle battle and exploration states.
- Updated the `block_number` and several `class_hash` and `original_class_hash` values in the deployment manifests (`manifest.json` and `manifest.toml`).
___
<tr>
<td>
<details>
<summary><strong>Worldmap.ts</strong><dd><code>Fix hexagon scaling condition logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/scenes/Worldmap.ts
- Fixed condition logic for scaling …
=> fixes #1197

client/src/three/components/InputManager.ts
___
- Fixed the army selection issue by refining the input handling logic.
- Removed unnecessary `mouseX` and `mouseY` properties and moved mouse position calculations directly into the event handler.
- Improved drag detection logic by adding a console log for debugging and ensuring proper cleanup of event listeners.
- Added a one-time mouseup event listener to remove the mousemove event listener, preventing potential memory leaks.
___
<tr>
<td>
<details>
<summary><strong>InputManager.ts</strong><dd><code>Fix army selection issue and improve input handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix #1201 army selection issue

client/src/three/components/ArmyManager.ts, client/src/three/components/LabelManager.ts
Enhancement
___
- Introduced a new `movingLabels` map in `ArmyManager` to track the movement of labels.
- Enhanced the `moveArmy` method to also initialize label movements.
- Updated the `update` method in `ArmyManager` to handle the progressive update of label positions.
- Added a new method `updateLabelPosition` in `LabelManager` to update the position of labels, ensuring only label objects are updated.
___
<tr>
<td>
<details>
<summary><strong>ArmyManager.ts</strong><dd><code>Add label movement tracking and updating</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Fix label translate

client/src/three/scenes/constants.ts
enhancement
___
- Added placeholder comments for various model paths in `constants.ts`.
- Updated `buildingModelPaths` to include a placeholder comment for `BuildingType.None`.
- Updated `StructureModelPaths` to include placeholder comments for `StructureType.Hyperstructure` and `StructureType.Settlement`.
- Updated `StructureLabelPaths` to include placeholder comments for `StructureType.Bank` and `StructureType.Settlement`.
___
<tr>
<td>
<details>
<summary><strong>constants.ts</strong><dd><code>Add placeholder comments for model paths in constants.ts</code>&nbsp; </dd></summary>
<hr>
client/src/three/scenes/constants.ts
<li>Added placeholder comments for …
=> placeholder models

client/src/main.tsx
enhancement
___
- Commented out the `accountChange` function and its event listener in `client/src/main.tsx`.
___
<tr>
<td>
<details>
<summary><strong>main.tsx</strong><dd><code>Disable account change event listener in main.tsx</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/main.tsx
- Commented out the `accountChange` function and its event listener.
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/1238/files#diff-d44e9e9aff3ba788632e2a3fce4725a069a66582be2291fee23f9101b4555f08">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table> …
=> remove dojo update

client/src/hooks/helpers/useRealm.tsx
=> fix settle quest

client/src/three/components/ArmyManager.ts
=> compute bounding sphere

client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/structures/construction/StructureCard.tsx, client/src/ui/containers/BaseContainer.tsx, client/src/ui/elements/SecondaryPopup.tsx, client/src/ui/elements/Tooltip.tsx, client/src/ui/modules/LoadingScreen.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/onboarding/Steps.tsx
=> Windows darker

.github/workflows/knip.yml, .github/workflows/lint.yml, .github/workflows/pr_agent.yml, .github/workflows/test-client.yml, .github/workflows/test-contracts.yml
This will cancel old running jobs on new commits to a PR/main branch push
=> Fix CI concurrency

client/src/ui/modules/navigation/TopMiddleNavigation.tsx
=> Use ViewOnMapIcon for realm view in map

client/src/ui/components/quest/QuestList.tsx
=> improve quest style

client/src/hooks/helpers/useResources.tsx, client/src/three/scenes/Hexception.ts, client/src/three/scenes/constants.ts, client/src/ui/components/entities/Entity.tsx, client/src/ui/components/military/ArmyChip.tsx, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx, client/src/ui/modules/navigation/RightNavigationModule.tsx, client/src/ui/modules/navigation/TopMiddleNavigation.tsx, client/src/ui/modules/world-structures/WorldStructuresMenu.tsx, contracts/src/systems/hyperstructure/contracts.cairo
Closes #1296
Closes #1275
Closes #1264
Closes #1263
=> Client fixes

client/src/hooks/store/_buildModeStore.tsx, client/src/ui/components/military/ArmyList.tsx
=> fix max_armies_count in client

client/src/three/GameRenderer.ts, client/src/three/geometry/HexagonGeometry.ts, client/src/three/helpers/GUIManager.ts, client/src/three/scenes/HexagonScene.ts, client/src/three/scenes/Hexception.ts, client/src/three/scenes/Worldmap.ts
Fixed https://github.com/BibliothecaDAO/eternum/issues/1280 bug with WASD keys block during typing
Added hexagon outlines on worldmap https://github.com/BibliothecaDAO/eternum/issues/1261 + changed map texture colorspace
Improved highling logic in build mode + fixed related bugs https://github.com/BibliothecaDAO/eternum/issues/1251
Added min distance to camera https://github.com/BibliothecaDAO/eternum/issues/1170
GUI controls removed from PROD client https://github.com/BibliothecaDAO/eternum/issues/1169
=> [ux/ui] fixes

client/src/dojo/contractComponents.ts, contracts/src/models/buildings.cairo, contracts/src/systems/buildings/contracts.cairo
=> Allow production pause

client/src/three/components/ArmyManager.ts, client/src/three/scenes/Worldmap.ts, client/src/three/systems/SystemManager.ts, client/src/three/systems/types.ts
=> Fixed army models when battling

contracts/src/systems/combat/contracts.cairo
=> contracts: only allow pillage if army has stamina

contracts/src/systems/bank/tests/liquidity.cairo, contracts/src/systems/combat/tests/army_buy_test.cairo, contracts/src/systems/combat/tests/army_create_test.cairo, contracts/src/systems/combat/tests/battle_leave_test.cairo, contracts/src/systems/combat/tests/battle_start_test.cairo, contracts/src/systems/map/tests.cairo, contracts/src/systems/transport/tests/travel_systems_tests.cairo
=> contracts: remove unused variables in test

client/src/dojo/modelManager/BattleManager.ts, contracts/manifests/dev/deployment/manifest.json, contracts/manifests/dev/deployment/manifest.toml, contracts/src/systems/combat/contracts.cairo
=> Fix delete of defensive army

client/src/dojo/modelManager/ArmyMovementManager.ts, client/src/dojo/modelManager/BattleManager.ts, client/src/dojo/modelManager/MarketManager.ts, client/src/dojo/modelManager/ProductionManager.ts, client/src/dojo/modelManager/StaminaManager.ts, client/src/dojo/modelManager/TileManager.ts, client/src/hooks/helpers/useResources.tsx, client/src/three/scenes/Hexception.ts, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/utils/utils.tsx
Fixes #1387
fixes hexception centered zoom point
clean up model managers
=> Bob client fixes

client/src/ui/components/trading/MarketOrderPanel.tsx
- sell order was only getting fulfilled partially because the wrong amount was being sent
- fixed
=> client: fix: send correct sell order values

client/src/dojo/modelManager/ArmyManager.ts, client/src/dojo/modelManager/BattleManager.ts, client/src/three/components/BattleManager.ts, client/src/three/systems/SystemManager.ts, client/src/three/systems/types.ts, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/modules/military/battle-view/Battle.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleSideView.tsx
=> fix: fix army delete and battle delete

client/src/ui/components/trading/MarketOrderPanel.tsx, client/src/ui/modules/chat/Chat.tsx
=> Add donkey used on accept trade

client/src/ui/elements/ArmyCapacity.tsx
=> Cap weight bar size

client/src/hooks/helpers/useEntities.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx, client/src/ui/modules/entity-details/EnemyArmies.tsx, contracts/manifests/dev/deployment/manifest.json, contracts/manifests/dev/deployment/manifest.toml, contracts/src/systems/combat/contracts.cairo
=> Prevent battling if immune

client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/modules/entity-details/BuildingEntityDetails.tsx, client/src/ui/modules/entity-details/EntityDetails.tsx
- remove pause/destroy if on other peoples realms
- styling of building details
=> fix pause + styling

client/src/dojo/contractComponents.ts, client/src/dojo/modelManager/__tests__/__LeaderboardManagerMock__.ts, client/src/ui/modules/stream/EventStream.tsx, contracts/src/systems/hyperstructure/contracts.cairo
=> improved hyperstructure event

client/src/dojo/modelManager/BattleManager.ts, client/src/dojo/modelManager/__tests__/BattleManager.test.ts, client/src/ui/elements/Tooltip.tsx, client/src/ui/modules/military/battle-view/BattleActions.tsx, client/src/ui/modules/military/battle-view/BattleHistory.tsx
This PR makes battle actions clearer and thus closes #1509
=> feat: enhance battle view

client/src/three/components/ArmyManager.ts, client/src/three/components/ArmyModel.ts, client/src/three/scenes/Worldmap.ts
Armies models optimizations
- added chunk system (only visible armies are added to mesh)
- added cache system
=> [client] chunk system for armies

client/src/hooks/helpers/useQuests.tsx, client/src/ui/components/quest/questDetails.tsx
=> Force to assign troops to defensive army

client/src/hooks/helpers/useGuilds.tsx, client/src/ui/components/worldmap/guilds/GuildInvites.tsx, client/src/ui/components/worldmap/guilds/GuildMembers.tsx, client/src/ui/components/worldmap/guilds/GuildsPanel.tsx, client/src/ui/components/worldmap/guilds/MyGuild.tsx, client/src/ui/components/worldmap/guilds/Whitelist.tsx
=> Add players list to invite from

client/src/dojo/contractComponents.ts, client/src/dojo/modelManager/ProductionManager.ts, client/src/ui/modules/world-structures/WorldStructuresMenu.tsx
=> add  production deadline client

client/src/dojo/createSystemCalls.ts, contracts/src/systems/combat/contracts.cairo, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/provider.ts
=> contracts: battle force start

contracts/src/models/config.cairo, contracts/src/systems/transport/contracts/travel_systems.cairo, contracts/src/systems/transport/tests/travel_systems_tests.cairo
=> contracts: make travel cost depend on steps

client/src/dojo/contractComponents.ts, client/src/ui/modules/stream/EventStream.tsx, contracts/src/models/event.cairo, contracts/src/systems/realm/contracts.cairo
=> settle realm in event stream

client/src/ui/components/military/ArmyList.tsx
=> prevent from creating armies outside of realms

contracts/src/systems/combat/contracts.cairo
=> contracts: only realm structures can have attack armies

client/src/three/helpers/GUIManager.ts, client/src/three/scenes/HexagonScene.ts, client/src/three/scenes/Worldmap.ts, client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/hints/HintModal.tsx, client/src/ui/components/quest/QuestInfo.tsx, client/src/ui/components/quest/QuestList.tsx, client/src/ui/components/quest/questDetails.tsx, client/src/ui/elements/ResourceIcon.tsx, client/src/ui/modules/stream/EventStream.tsx, contracts/formula/resources.py, contracts/manifests/dev/deployment/manifest.json, contracts/manifests/dev/deployment/manifest.toml, sdk/packages/eternum/src/constants/resources.ts
- #1352 (iteration still needs work)
- #1427 
Also changed army select from right to left - feels more natural
Fixed issue with env so white line disapears
=> add icons, change click, fix env

contracts/src/models/combat.cairo
Ensure that if the deduction makes the health less than one troop, the troop dies immediately
e.g if single troop health = 7 * 1000(normalization), then a troop with 3 soldiers will have
health a total health of 7_000 * 3 =  21_000.
if deduction is 80 per second, we want it such that deduction happens
at the rate of 80 per second till it takes 7_000 * (3 -1) =14_000 health,
then after that, the next step depletes the health completely. i.e to 0 since it will make the health 
less than what a single troop should have
the contracts already work this way. it's just the time estimation that would have been wrong so this pr fixes that
=> contracts: fix battle time estimation bug

contracts/src/models/combat.cairo
=> [contracts] resolves invulnerable state in siege #1614

client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/quest/questDetails.tsx, client/src/ui/components/trading/MarketModal.tsx, client/src/ui/modules/chat/Chat.tsx, client/src/ui/modules/entity-details/BuildingEntityDetails.tsx, client/src/ui/utils/utils.tsx
=> feat: Update lords in real time in market modal + army chip in military menu

client/src/hooks/helpers/useQuests.tsx, client/src/ui/components/military/ArmyList.tsx, client/src/ui/components/quest/questDetails.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx
=> Separate defensive & offensive creation quest condition

contracts/src/models/resources.cairo
=> fix  #1668 max resource not limited by storehouse limit

client/src/ui/components/worldmap/structures/StructureListItem.tsx
=> Update immunity time left on selected structure change

client/src/ui/components/trading/MarketOrderPanel.tsx
=> Fix buy order default amount between buys + styling

client/src/hooks/helpers/useStructures.tsx, client/src/three/scenes/Hexception.ts, client/src/ui/components/resources/InventoryResources.tsx, client/src/ui/components/resources/RealmResourcesIO.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx, client/src/ui/modules/entity-details/BuildingEntityDetails.tsx, client/src/ui/modules/entity-details/CombatEntityDetails.tsx, client/src/ui/modules/navigation/LeftNavigationModule.tsx
+ sort resource inventory
Fixes #1650
=> Add realm resource prod + consumption info

client/src/hooks/helpers/useGuilds.tsx, client/src/hooks/helpers/useHyperstructures.tsx, client/src/hooks/helpers/useShardMines.tsx, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/components/worldmap/leaderboard/PlayersLeaderboard.tsx, client/src/ui/elements/AddressSelect.tsx, client/src/ui/elements/SelectResource.tsx, client/src/ui/modules/chat/Chat.tsx, client/src/ui/modules/entity-details/BuildingEntityDetails.tsx
Fixes #1688
Fixes #1694
Fixes #1691
Fixes #1697
=> Enh/various UI fixes

client/src/ui/components/bank/LiquidityResourceRow.tsx, client/src/ui/components/bank/LiquidityTable.tsx
- Adjust production cost of resource based on output amount 
- fix hidden popup for 1st row in table
Fixes #1713
=> Fix Amm production cost popup

client/src/ui/components/resources/EntityResourceTable.tsx, client/src/ui/components/resources/ResourceChip.tsx
=> feat: Stop resource production when max cap is reached

client/src/dojo/modelManager/BattleManager.ts, client/src/dojo/modelManager/__tests__/BattleManager.test.ts, client/src/ui/modules/military/battle-view/BattleProgressBar.tsx
=> fix: timing issues in structure battles

client/src/ui/modules/navigation/TopMiddleNavigation.tsx
=> Add time until next cycle in tooltip

client/src/ui/components/trading/MarketModal.tsx
=> Fix best sell price

client/src/hooks/helpers/useResources.tsx, client/src/ui/modules/chat/Chat.tsx, client/src/ui/modules/stream/EventStream.tsx
=> feat: add chat minimizing feature

client/src/ui/components/construction/SelectPreviewBuilding.tsx, client/src/ui/components/hints/Buildings.tsx, client/src/ui/components/hints/Resources.tsx, client/src/ui/components/hints/TheMap.tsx
=> Fix broken lordpedia pages

contracts/formula/battle_time.js
=> battle time script

client/src/ui/components/military/ArmyChip.tsx, client/src/ui/components/military/ArmyManagementCard.tsx, client/src/ui/modules/social/PlayerId.tsx, client/src/ui/modules/stream/EventStream.tsx
=> Fix events

client/src/three/scenes/Hexception.tsx, client/src/three/scenes/Worldmap.ts, client/src/three/systems/SystemManager.ts
Now the explored hexes do not disappear when a new realm (or other structure) is settled
=> fix: disappearing chunks

client/src/ui/components/bank/Swap.tsx
hot fix in client,
will need to look into the contracts to fix true issue
=> fix amm rounding

sdk/packages/eternum/src/constants/global.ts
the config has already been set on remote katana. we just need to merge this so client is correct
=> client: increase donkey capacity by 4x

client/src/hooks/helpers/useEntities.tsx, client/src/hooks/store/useMarketStore.tsx, client/src/ui/modules/entity-details/CombatEntityDetails.tsx, client/src/ui/modules/entity-details/Entities.tsx, client/src/ui/modules/military/Military.tsx, contracts/manifests/dev/deployment/manifest.json, contracts/manifests/dev/deployment/manifest.toml, pnpm-lock.yaml
=> remove dupe hook

.github/workflows/test-contracts.yml, contracts/scripts/contracts.sh, contracts/scripts/system_models.json, contracts/src/models/owner.cairo, contracts/src/systems.cairo, contracts/src/systems/combat/contracts.cairo, contracts/src/systems/ownership/contracts.cairo, contracts/src/systems/ownership/tests.cairo, contracts/src/utils/testing/config.cairo, contracts/src/utils/testing/constants.cairo, contracts/src/utils/testing/world.cairo
=> [contracts]: Ownership transfer

client/src/ui/components/battles/BattleListItem.tsx, client/src/ui/components/military/ArmyChip.tsx, client/src/ui/components/structures/worldmap/StructureCard.tsx, client/src/ui/components/worldmap/structures/StructureLabel.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx, client/src/ui/modules/entity-details/Entities.tsx
=> [client] show more realm info on hover

contracts/formula/battle_time.js, contracts/src/models/combat.cairo, contracts/src/models/config.cairo, contracts/src/systems/combat/tests/battle_leave_test.cairo, contracts/src/utils/testing/config.cairo, sdk/packages/eternum/src/config/index.ts, sdk/packages/eternum/src/constants/global.ts, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/common.ts, sdk/packages/eternum/src/types/provider.ts
limit battle time using the formula `(x * n)/(n + 100_000) * smaller_army_strength / bigger_army_strength`
where x is the max time, and n is the time it would have been if unlimited
=> [config + contract] battle time limit

client/src/dojo/createSystemCalls.ts, client/src/ui/components/entities/Entity.tsx, client/src/ui/components/resources/DepositResources.tsx, client/src/ui/components/trading/ResourceArrivals.tsx, client/src/ui/components/trading/TransferBetweenEntities.tsx, sdk/packages/eternum/src/provider/index.ts, sdk/packages/eternum/src/types/provider.ts
=> feat: deposit all button + new transfer after completing one

client/src/three/scenes/Hexception.tsx, client/src/three/scenes/Worldmap.ts, client/src/ui/modules/entity-details/CombatEntityDetails.tsx
=> [client] default hex

client/src/ui/modules/navigation/LeftNavigationModule.tsx
=> [client] left navigation menu issue on small screens

client/src/hooks/helpers/useQuests.tsx
=> Fix quest update on optimitic build

.knip.json, client/src/ui/components/structures/worldmap/StructureCard.tsx, client/src/ui/components/worldmap/structures/StructureListItem.tsx
=> Add showImmunity prop to StructureCard and StructureListItem components

client/src/dojo/modelManager/LeaderboardManager.ts
=> fix: hyperstructure shares

contracts/game/src/models/owner.cairo, contracts/game/src/models/resource/production/building.cairo, contracts/game/src/models/structure.cairo, contracts/game/src/systems/bank/contracts/bank.cairo, contracts/game/src/systems/bank/contracts/liquidity.cairo, contracts/game/src/systems/bank/contracts/swap.cairo, contracts/game/src/systems/combat/contracts/troop_battle.cairo, contracts/game/src/systems/combat/contracts/troop_management.cairo, contracts/game/src/systems/combat/contracts/troop_movement.cairo, contracts/game/src/systems/combat/tests/test_troop_management.cairo, contracts/game/src/systems/hyperstructure/contracts.cairo, contracts/game/src/systems/production/contracts.cairo, contracts/game/src/systems/realm/contracts.cairo, contracts/game/src/systems/resources/contracts/resource_bridge_systems.cairo, contracts/game/src/systems/resources/contracts/resource_systems.cairo, contracts/game/src/systems/trade/contracts/trade_systems.cairo, contracts/game/src/systems/utils/resource.cairo
=> contracts: update structure model

config/deployer/config.ts, config/environments/_shared_.ts, contracts/game/src/models/config.cairo, contracts/game/src/models/position.cairo, contracts/game/src/systems.cairo, contracts/game/src/systems/combat/contracts/troop_movement.cairo, contracts/game/src/systems/hyperstructure/contracts.cairo, contracts/game/src/systems/resources/contracts/resource_systems.cairo, contracts/game/src/systems/trade/contracts/trade_systems.cairo, contracts/game/src/systems/utils/distance.cairo, contracts/game/src/systems/utils/hyperstructure.cairo, contracts/game/src/systems/utils/mine.cairo, contracts/game/src/systems/utils/resource.cairo, packages/core/src/dojo/contract-components.ts, packages/core/src/provider/index.ts, packages/core/src/types/common.ts, packages/core/src/types/provider.ts
- allow players find hypers on the map with the highest chance at the center of the map and less chance with distance
- hyperstructure foundations need to be fought and won over
=> feat: allow players find hyperstructures on the map

config/deployer/config.ts, config/environments/_shared_.ts, contracts/game/src/models/config.cairo, contracts/game/src/models/hyperstructure.cairo, contracts/game/src/systems/hyperstructure/contracts.cairo, contracts/game/src/systems/structure/contracts.cairo, contracts/game/src/systems/utils/hyperstructure.cairo, packages/core/src/dojo/contract-components.ts, packages/core/src/provider/index.ts, packages/core/src/types/common.ts, packages/core/src/types/provider.ts
- allow hyp foundation to construct from its balance.
- use hyperstructure count during foundation find probability calc
=> Update hyperstructure foundations

client/apps/game/src/ui/modules/onboarding/steps.tsx, client/apps/landing/schema.graphql, client/apps/landing/src/components/modules/bridge-fees.tsx, client/apps/landing/src/hooks/gql/graphql.ts, config/deployer/config.ts, config/environments/_shared_.ts, contracts/game/src/models/config.cairo, contracts/game/src/models/hyperstructure.cairo, contracts/game/src/systems.cairo, contracts/game/src/systems/hyperstructure/contracts.cairo, contracts/game/src/systems/realm/contracts.cairo, contracts/game/src/systems/resources/contracts/resource_bridge_systems.cairo, contracts/game/src/systems/resources/tests/resource_bridge_system_tests.cairo, contracts/game/src/systems/season/contracts.cairo, contracts/game/src/systems/utils/bridge.cairo, contracts/game/src/systems/utils/erc20.cairo, contracts/game/src/systems/utils/hyperstructure.cairo, contracts/game/src/systems/utils/resource.cairo, contracts/game/src/systems/utils/village.cairo, packages/core/src/dojo/contract-components.ts, packages/core/src/managers/config-manager.ts, packages/core/src/provider/index.ts, packages/core/src/types/common.ts, packages/core/src/types/provider.ts, packages/react/src/hooks/helpers/use-bank.ts
- refactor resource portal to match new docs spec
=> resource bridge: update resource bridge mechanics

contracts/game/manifest_sepolia.json, contracts/game/src/models/resource/resource.cairo
- fix bug that didnt allow resource weight get updated
=> contracts: fix resource weight bug

client/apps/bot/llm.txt, client/apps/game-docs/docs/components/StartingMilitary.tsx, client/apps/game-docs/docs/pages/mechanics/victory.mdx, client/public/llm.txt
Revise the activation process for Hyperstructure Foundations in the documentation and redact specific military resource information for clarity.
=> Update game documentation and redact military details

contracts/game/src/systems/utils/resource.cairo
=> contracts: ensure donkeys cant be raided

contracts/game/src/models/config.cairo, contracts/game/src/systems/bank/contracts/liquidity.cairo, contracts/game/src/systems/config/contracts.cairo, contracts/game/src/systems/resources/contracts/resource_bridge_systems.cairo, contracts/game/src/systems/utils/bridge.cairo
=> contracts: allow lp exit without owning structure

contracts/village_pass/src/contract.cairo
- add batch transfer function to transfer any amount of tokens owned by an address
=> village pass: add simple batch transfer function

client/apps/game/src/three/managers/minimap.ts
=> feat: show coords on minimap

client/apps/game/src/ui/modules/ws-chat/chat.tsx, client/apps/game/src/ui/modules/ws-chat/components/chat/MessageGroup.tsx, client/apps/game/src/ui/modules/ws-chat/components/chat/MessageInput.tsx, client/apps/game/src/ui/modules/ws-chat/useChatStore.ts
The current chat has a very inconvenient UX, making it almost useless in the game. There were problems with both the visual part and solving communication issues between players.
Changes in this PR were made to solve these problems and make the chat comfortable and useful.
List of changes:
1. The chat's appearance has been redesigned to be less noticeable with no borders and a transparent background. The placement of UI elements follows proven UX practices from popular online games.
2. The old messaging system could confuse users because unread badges didn't show if the receiver was offline when the message was sent or if they reloaded the page without reading the message. In this update, a feature was added to save unread message information between page reloads, so now you can't miss a …
=> [feat] chat module update

client/apps/game-docs/docs/pages/blitz/key-concepts.mdx, client/apps/game-docs/docs/pages/blitz/materials/automation.mdx, client/apps/game-docs/docs/pages/blitz/materials/production.mdx, client/apps/game-docs/docs/pages/blitz/materials/resources.mdx, client/apps/game-docs/docs/pages/blitz/military/armies.mdx, client/apps/game-docs/docs/pages/blitz/military/stamina-and-biomes.mdx, client/apps/game-docs/docs/pages/blitz/realms/realm.mdx, client/apps/game-docs/docs/pages/blitz/victory.mdx, client/apps/game-docs/docs/pages/blitz/world-physics.mdx, client/apps/game-docs/docs/pages/blitz/worldmap-movement/worldmap.mdx, client/apps/game-docs/vocs.config.ts
- Removed outdated links and improved navigation in vocs.config.ts.
- Revised key concepts in various documentation pages, including troop production, military mechanics, and resource management.
- Enhanced descriptions for bridging and scoring systems, ensuring consistent terminology.
- Updated sections on realms and world map mechanics to clarify player registration and positioning.
- Fixed formatting issues and ensured all references are accurate and up-to-date.
=> Doc Review for Initial Release

client/apps/game-docs/docs/pages/blitz/key-concepts.mdx, client/apps/game-docs/docs/pages/blitz/materials/automation.mdx, client/apps/game-docs/docs/pages/blitz/materials/production.mdx, client/apps/game-docs/docs/pages/blitz/materials/resources.mdx, client/apps/game-docs/docs/pages/blitz/military/armies.mdx, client/apps/game-docs/docs/pages/blitz/military/stamina-and-biomes.mdx, client/apps/game-docs/docs/pages/blitz/realms/realm.mdx, client/apps/game-docs/docs/pages/blitz/victory.mdx, client/apps/game-docs/docs/pages/blitz/world-physics.mdx, client/apps/game-docs/docs/pages/blitz/worldmap-movement/worldmap.mdx, client/apps/game-docs/vocs.config.ts
* Documentation Review
- Removed outdated links and improved navigation in vocs.config.ts.
- Revised key concepts in various documentation pages, including troop production, military mechanics, and resource management.
- Enhanced descriptions for bridging and scoring systems, ensuring consistent terminology.
- Updated sections on realms and world map mechanics to clarify player registration and positioning.
- Fixed formatting issues and ensured all references are accurate and up-to-date.
* Expand on Victory documentation
- Updated the scoring system to clarify how Victory Points (VP) are awarded for various actions, including exploring tiles and claiming structures.
- Introduced a detailed table outlining VP awarded for specific actions to improve clarity and user understanding.
* …
=> Doc Review for Initial Release (#3486)

.prettierignore, client/apps/bot/llm.txt, client/apps/game-docs/docs/components/ExplorationRewards.tsx, client/apps/game-docs/docs/components/RelicTable.tsx, client/apps/game-docs/docs/pages/blitz/key-concepts.mdx, client/apps/game-docs/docs/pages/blitz/materials/bridging.mdx, client/apps/game-docs/docs/pages/blitz/materials/production.mdx, client/apps/game-docs/docs/pages/blitz/materials/relics.mdx, client/apps/game-docs/docs/pages/blitz/materials/resources.mdx, client/apps/game-docs/docs/pages/blitz/materials/transfers-and-trade.mdx, client/apps/game-docs/docs/pages/blitz/realms/buildings.mdx, client/apps/game-docs/docs/pages/blitz/realms/realm.mdx, client/apps/game-docs/docs/pages/blitz/victory.mdx, client/apps/game-docs/docs/pages/blitz/world-physics.mdx, client/apps/game-docs/docs/pages/blitz/world-structures.mdx, client/apps/game-docs/docs/pages/blitz/worldmap-movement/movement.mdx, client/apps/game-docs/docs/pages/blitz/worldmap-movement/worldmap.mdx, client/apps/game-docs/docs/pages/eternum/key-concepts.mdx, client/apps/game-docs/docs/pages/eternum/tribes.mdx, client/apps/game-docs/docs/pages/overview/entry.mdx, client/apps/game-docs/docs/pages/overview/introduction.mdx, client/apps/game-docs/docs/pages/overview/loot-chests.mdx, client/public/llm.txt
Update game documentation for clarity and balance adjustments. Revised ExplorationRewards quantities, improved descriptions of Labor and Essence mechanics, and adjusted Victory Points for various actions. Enhanced details on world structures and materials, including bridging and production processes.
=> Docs Update
