contracts/scripts/set_config.sh

When you call set_config.sh. it prompts you to add a delay. Can be integer like 2 or floats like 0.3 seconds
this is due to new dojo update where if delay is 0 (by default), then there are nonce issues.

fix-add-delay

---

client/package.json
client/src/components/SettingsComponent.tsx
client/src/components/SignUpComponent.tsx
client/src/components/cityview/realm/labor/LaborBuild.tsx
client/src/components/cityview/realm/trade/CreateOffer.tsx
client/src/containers/TopContainer.tsx
client/src/elements/SecondaryPopup.tsx
client/src/elements/Steps.tsx

- Labor, Settings and Create offer popups are now draggable.
- After dragging popup position is saved to localStorage, and this position will be used as default after reopening the popup between game sessions.
- Clicking on popup now moves it to top level z-index
- Last opened popup appears on top level z-index

feat: draggable popups

---

client/src/components/cityview/realm/RealmLaborComponent.tsx
client/src/components/cityview/realm/RealmManagementComponent.tsx
client/src/components/cityview/realm/RealmResourcesComponent.tsx
client/src/components/cityview/realm/RealmTradeComponent.tsx
client/src/components/cityview/realm/SmallResource.tsx
client/src/components/cityview/realm/trade/AcceptOffer.tsx
client/src/components/cityview/realm/trade/Market/MarketOffer.tsx
client/src/components/cityview/realm/trade/MyOffers/MyOffer.tsx
client/src/components/worldmap/RealmsListPanel.tsx
client/src/components/worldmap/WorldMapMenuComponent.tsx
client/src/components/worldmap/hyperstructures/FeedHyperstructure.tsx
client/src/components/worldmap/hyperstructures/HyperstructuresPanel.tsx
client/src/elements/SelectableResource.tsx
client/src/elements/Tooltip.tsx
client/src/hooks/store/useUIStore.tsx
client/src/layouts/World.tsx

few ui fixes:
1.  Now tooltips don't causing scrolls and aren't cropped by parent container, also they will follow player's cursor position
Now we can easily add more help tooltips with detailed explanations of UI in any place.
3. Fixed width of "Accept offer" popup

feat: floating tooltips, popup width

---

contracts/src/systems/combat/contracts.cairo

- fix bug that makes total defence of the target or attacker =~1
- the issue is that we used a `+` sign where we were supposed to use a `*` sign

fix combat success chance bug

---

contracts/src/systems/transport/contracts/caravan_systems.cairo
contracts/src/systems/transport/contracts/transport_unit_systems.cairo
contracts/src/systems/transport/contracts/travel_systems.cairo
contracts/src/systems/transport/interface/caravan_systems_interface.cairo
contracts/src/systems/transport/interface/transport_unit_systems_interface.cairo
contracts/src/systems/transport/tests/caravan_systems_tests.cairo
contracts/src/systems/transport/tests/transport_unit_systems_tests.cairo
contracts/target/dev/manifest.json
contracts/target/release/manifest.json

- added a way to disassemble caravan into its transport units in `caravan_systems.disassemble`
- added a way to return unused free transport units in `transport_unit_systems.return_free_units`

feat: caravan disassembly and free transport unit return

---

contracts/src/models.cairo
contracts/src/models/order.cairo
contracts/src/systems.cairo
contracts/src/systems/combat/contracts.cairo
contracts/src/systems/combat/interface.cairo
contracts/src/systems/hyperstructure.cairo
contracts/src/systems/hyperstructure/contracts.cairo
contracts/src/systems/hyperstructure/interface.cairo
contracts/target/dev/manifest.json
contracts/target/release/manifest.json

- changed the field `target_realm_entity_id` in `CombatOutcome` event struct to `target_entity_id`
- added endpoints to start building hyperstructure and to complete hyperstructure
- created a way to keep tract of order bonus
- fixed an issue with attack calculation:
if an attacker's unboosted attack value was `20` for example, and they had both the realm level bonus (25%) and hyperstructure bonus(25%), you would expect that they new total attack value would be `20 + (25/100 * 20) + (25/100 * 20)` == `20 + 5 + 5` == `30`. however, the calculation would be `20 * 125/100 * 125 / 100` which would equal `31.25`

conquest update

---

contracts/src/models/map.cairo
contracts/src/models/position.cairo
contracts/src/systems/map/contracts.cairo
contracts/src/systems/map/interface.cairo
contracts/src/systems/map/tests.cairo
contracts/src/systems/realm/contracts.cairo
contracts/src/systems/realm/tests.cairo
contracts/target/dev/manifest.json

- renamed `ExploredMap` to `Tile`
- mark realm tile as explored immediately it is created
- only allow exploration of tiles near already explored tiles

contract: nearby tile exploration

---

contracts/scripts/set_config.sh
contracts/src/models.cairo
contracts/src/models/capacity.cairo
contracts/src/models/combat.cairo
contracts/src/models/config.cairo
contracts/src/models/inventory.cairo
contracts/src/models/tick.cairo
contracts/src/systems/combat/contracts.cairo
contracts/src/systems/config/contracts.cairo
contracts/src/systems/config/interface.cairo
contracts/src/systems/map/contracts.cairo
contracts/src/systems/map/interface.cairo
contracts/src/systems/realm/contracts.cairo
contracts/src/systems/resources/contracts.cairo
contracts/src/systems/transport/contracts/caravan_systems.cairo
contracts/src/systems/transport/contracts/travel_systems.cairo
contracts/src/systems/transport/interface/travel_systems_interface.cairo
contracts/target/dev/manifest.json

- created tick so that actions such as travel may be limited by tick
- created a travel_hex function for hex travel. Travel is instantanious but is limited by amount of hex moves per tick
- allow exploration to be done by armies and use up all tick moves during exploration
- updated MapExplored Event
- Add travel time and travel path to `Travel` event

contracts: add hex tick, travel, army exploration

---

.github/workflows/test.yml

- update CI dojo version
- test won't run in CI though because of this issue https://github.com/dojoengine/dojo/issues/1646 but to confirm that it works, `sozo build` should work in CI and `sozo test` should be attempted in CI

CI: update dojo version in CI

---

client/src/components/worldmap/ChooseActionPopup.tsx
client/src/hooks/helpers/useCombat.tsx
contracts/manifests/deployments/KATANA.toml
sdk/packages/eternum/src/provider/index.ts

- Allow for multiple hex exploration before return to realm
- batch calls to transfer inventory items to realm to avoid hitting cairo step limit
- only enable explore button when army has enough capacity to carry reward

client: allow for multiple hex exploration before return to realm

---

client/src/components/cityview/realm/combat/raids/AttackRaidsPopup.tsx
client/src/components/cityview/realm/combat/raids/Raid.tsx
client/src/hooks/helpers/useCombat.tsx

resolves #441
___
___
- Simplified the fallback text in `AttackRaidsPopup.tsx` to just "Attacking" for clarity when no defending realm is specified.
- Added a condition in `Raid.tsx` to only show the "Attack Realm" button when the raider is on a watchtower, enhancing user experience by clarifying when attacks can be initiated.
- Renamed and refined a function in `useCombat.tsx` for fetching watchtower information, improving code readability and accuracy.
___
<tr>
<td>
<details>
<summary><strong>AttackRaidsPopup.tsx</strong><dd><code>Simplify Attack Popup Text</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: not show attack if not on realm

---

client/src/components/worldmap/hexagon/utils.tsx
contracts/scripts/set_config.sh

solves #468
___
___
- Limited pathfinding to a maximum hex distance to prevent excessive travel.
- Adjusted the maximum moves per tick from 4 to 3 in the game's configuration script, aligning game mechanics with intended limits.
___
<tr>
<td>
<details>
<summary><strong>utils.tsx</strong><dd><code>Limit Pathfinding to Maximum Hex Distance</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/components/worldmap/hexagon/utils.tsx
<li>Added a condition to check if the distance is within the maximum <br>allowed hex distance …

fix: only 3 hex distance travel

---

contracts/src/models/buildings.cairo
contracts/src/models/config.cairo
contracts/src/models/production.cairo
contracts/src/models/resources.cairo

___
- Introduced `ProductionInputImpl` for better management of production inputs and their exhaustion ticks.
- Enhanced production and resource models to accurately calculate and update end ticks based on resource consumption and production rates.
- Added debugging support in configuration model and improved clarity in building models by renaming traits.
- Expanded testing to cover new functionalities and ensure the accuracy of resource and production calculations.
___
<tr>
<td>
<details>
<summary><strong>buildings.cairo</strong><dd><code>Enhancements and Bug Fixes in Building Models</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Bug fixes and tests

---

contracts/manifests/dev/base/contracts/eternum_systems_buildings_contracts_building_systems.toml
contracts/manifests/dev/manifest.json
contracts/manifests/dev/manifest.toml
contracts/src/models/buildings.cairo

- fix production end tick bug
___
___
- Updated contract hashes in TOML and JSON configurations to reflect new contract versions.
- Modified block numbers in manifest files to the latest block (334) for accurate contract deployment tracking.
- Enhanced resource production logic in Cairo contracts to dynamically update the end tick based on the least resource finish tick, improving accuracy in resource management.
- Ensured `produced_resource_type` is set to a default value if not explicitly specified, enhancing robustness in building model handling.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details> …

production bug fix: use accurate end tick

---

client/src/hooks/store/_buildModeStore.tsx
client/src/shaders/placeholderMaterial.tsx
client/src/ui/components/construction/BuildArea.tsx
client/src/ui/components/construction/GroundGrid.tsx

1. Free hexagons are now highlighted if player is in build mode
2. Added placeholder shader
___
___
- Introduced a new shader material for visually indicating potential building placements in build mode.
- Enhanced build mode state management to better handle hovered and selected states.
- Refactored BuildingPreview component for improved performance and readability.
- Improved user experience in build mode by highlighting free hexagons with a new placeholder shader.
- Fixed a bug where the hovered hex state was not cleared after placing a building.
___
<tr>
<td>
<details>
<summary><strong>_buildModeStore.tsx</strong><dd><code>Enhance …

feat: construction ux 

---

client/src/hooks/store/useUIStore.tsx
client/src/ui/components/construction/SelectPreviewBuilding.tsx
client/src/ui/components/worldmap/hexagon/HexLayers.tsx
client/src/ui/modules/navigation/TopMiddleNavigation.tsx

1. Fixed scroll in construction menu #652 
2. Improved camera transition between worldmap view and hexception view #600 
enhancement
___
- Removed dependency on `useAutoAnimate` from `@formkit/auto-animate/react`, which simplifies the component by removing unnecessary animations.
- Updated the main container div by removing the `overflow-hidden` class and the `ref` attribute, making the component structure cleaner and potentially improving performance.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Remove Auto Animation and Simplify Container in Building Selection</code></dd></summary>
<hr> …

fix: scrollable build menu, camera transition

---

contracts/Scarb.toml

Had an issue with `sozo build`, turns out you have to add the `v` in front of the tag in the `Scarb.toml` for the dojo version

Add v to tag of dojo version in scarb.toml

---

client/src/hooks/helpers/useExplore.tsx
client/src/hooks/helpers/useTravel.tsx

bug_fix
___
- Added error handling in `useExplore` and `useTravel` hooks to revert animations if transactions fail.
- This update ensures that both explorers and traveling entities return to their original positions if the associated blockchain transactions do not succeed.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>useExplore.tsx</strong><dd><code>Add error handling to revert explorer animations on failure</code></dd></summary>
<hr>
client/src/hooks/helpers/useExplore.tsx
<li>Added error handling to revert animations if the <code>explore</code> function <br>fails.<br> <li> This ensures that the explorer's position is reset to the original <br>state upon …

solves  #669 by reverting explore and travel animation if tx fail

---

contracts/scripts/system_models.json
contracts/src/models/structure.cairo
contracts/src/systems/bank/contracts/bank_systems.cairo
contracts/src/systems/realm/contracts.cairo

resolves #625
___
enhancement
___
- Introduced a new `StructureCount` model in `structure.cairo` to track structures per coordinate and ensure only one structure exists per hex.
- Updated `bank_systems.cairo` and `realm_systems.cairo` to include checks using `StructureCount` to prevent multiple structures from being placed on the same hex.
- This change enforces a rule that only one structure can exist per hex, enhancing the game's strategic elements and preventing errors from multiple structures in a single location.
___
<tr>
<td>
<details>
<summary><strong>structure.cairo</strong><dd><code>Add StructureCount Model to Enforce Single Structure …

allow only one structure per hex

---

client/src/ui/components/construction/SelectPreviewBuilding.tsx

enhancement
___
- Added a new UI section in `SelectPreviewBuilding.tsx` to display ongoing costs per cycle for each building.
- Implemented a check to display the costs only if `resourceProduced` is not zero and `ongoingCost` is defined.
- Costs are now displayed in a grid format, showing the resource and its amount required per cycle.
- Added a debug log statement to help trace the values of ongoing costs during development.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Enhance Building Info Component with Ongoing Cost Display</code></dd></summary>
<hr>
client/src/ui/components/construction/SelectPreviewBuilding.tsx …

cost cycle fix

---

client/src/ui/modules/transactions/Transactions.tsx

always show transaction status component above all others so the error is always visible.
transaction status is usually hidden under pillage screen so people cant see error
___
enhancement
___
- The `div` element wrapping the transaction status messages in `Transactions.tsx` now has a `zIndex` of 100. This change ensures that the transaction status is always visible, addressing the issue where it could be hidden under other UI elements.
___
<tr>
<td>
<details>
<summary><strong>Transactions.tsx</strong><dd><code>Ensure Transaction Status Component Visibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

show transaction status component above all others

---

client/src/dojo/modelManager/ProductionManager.ts

Bug fix
___
- Fixed an issue where the default value for `quantity` was incorrectly set as a BigInt ("0n") instead of a string ("0").
- Enhanced the store capacity calculation by changing the multiplier from 100 to 1000, increasing the capacity calculation.
___
<tr>
<td>
<details>
<summary><strong>ProductionManager.ts</strong><dd><code>Fix and Enhance Store Capacity Calculation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/dojo/modelManager/ProductionManager.ts
<li>Changed default value of <code>quantity</code> from "0n" to "0".<br> <li> Modified the formula for …

fix store capacity bug

---

client/src/ui/components/construction/SelectPreviewBuilding.tsx

bug_fix
___
- Fixed a precision error in the `checkBalance` function within `SelectPreviewBuildingMenu`. The balance calculation was previously multiplied by an extra 1000, which has been removed to correct the resource balance check.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Fix precision error in balance calculation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/construction/SelectPreviewBuilding.tsx
<li>Corrected the calculation of balance check in <code>checkBalance</code> function by <br>removing an …

fix precision bug with cost

---

client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx

enhancement
solves #743 
___
- Swapped the positions of `<ArmiesAtLocation />` and `<Battle />` components to enhance the user interface in the `HexagonInformationPanel`.
___
<tr>
<td>
<details>
<summary><strong>HexagonInformationPanel.tsx</strong><dd><code>Swap Positions of Components in HexagonInformationPanel</code>&nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
<li>Swapped the positions of <code><ArmiesAtLocation /></code> and <code><Battle /></code> <br>components within the <code>HexagonInformationPanel</code>.<br>
</details>
</td>
<td><a …

fix: switch positions of structures and battles in Location details OSWindow

---

client/src/ui/components/construction/SelectPreviewBuilding.tsx
client/src/ui/components/military/Battle.tsx

solves #744
___
___
- Exported `BUILDING_IMAGES_PATH` from `SelectPreviewBuilding.tsx` for use in other components.
- Improved the Pillage History component in `Battle.tsx` by:
- Adding early return if component is unmounted during event subscription.
- Enhancing the UI layout to be more centered and adding visual cues for army ID and outcomes.
- Displaying images for destroyed buildings based on their type.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Export BUILDING_IMAGES_PATH for Reuse</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix pillage history not showing + improve layout

---

client/src/ui/components/military/Battle.tsx
contracts/src/models/loyalty.cairo
contracts/src/systems/combat/contracts.cairo

___
- Added a new state "No Winner" to the battle outcome display in the UI to handle cases without a clear winner.
- Simplified the loyalty calculation in the Cairo contract by removing unnecessary initial checks.
- Enhanced the combat system by preventing self-attacks and adjusting the strength and attack probability calculations to factor in loyalty.
___
<tr>
<td>
<details>
<summary><strong>Battle.tsx</strong><dd><code>Update Winner Display Logic in Pillage History</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/military/Battle.tsx
<li>Updated the …

Combat pillage fixes

---

client/src/ui/elements/ResourceCost.tsx

___
enhancement
___
- Added conditional text coloring to the `ResourceCost` component to visually indicate when the balance is less than the amount, using red color for deficits and green for normal or surplus values.
- Included a console log for debugging purposes, which logs balance, amount, and the resulting color.
- Minor adjustments to JSX formatting and spacing for better readability and consistency.
___
<tr>
<td>
<details>
<summary><strong>ResourceCost.tsx</strong><dd><code>Enhance Resource Cost Component with Conditional Text Coloring</code></dd></summary>
<hr>
client/src/ui/elements/ResourceCost.tsx
<li>Added logic to change text color based on …

show missing balance in red

---

contracts/src/models/buildings.cairo

bug_fix
___
- Ensures that when a building is destroyed, all its relevant attributes are reset to default values, preventing any unintended carryover of state.
___
<tr>
<td>
<details>
<summary><strong>buildings.cairo</strong><dd><code>Properly Reset Building Attributes on Destruction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
contracts/src/models/buildings.cairo
<li>Reset <code>produced_resource_type</code> and <code>bonus_percent</code> attributes of a <br>building when it is destroyed.<br>
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/779/files#diff-d98a082b4990bd2f45a454b6fbeef40ee7acbd …

destroy building properly

---

contracts/manifests/dev/manifest.json
contracts/manifests/dev/manifest.toml
contracts/manifests/prod/manifest.json
contracts/manifests/prod/manifest.toml
contracts/src/models/weight.cairo

Closes #755
___
enhancement
___
- Updated `class_hash` and `original_class_hash` for multiple `DojoContract` entries in both development and production manifests.
- Removed a `DojoModel` entry related to `eternum::models::buildings::building_quantity` from both development and production manifests.
- Added a new data field `timestamp` to an event in the production manifest.
- Improved the assert message for weight deduction in the `weight.cairo` model to be more explicit.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update class hashes and remove specific DojoModel entry.</code>&nbsp; </dd></summary>
<hr> …

enh: Change weight deduct assert message to be more explicit

---

client/src/ui/utils/Camera.tsx

Bug fix
___
- Fixed camera angle constraints for the world map view by adding `minAzimuthAngle` and `maxAzimuthAngle` properties to the `CameraControls` component.
- Set the azimuth angle limits conditionally based on whether the view is a map view.
___
<tr>
<td>
<details>
<summary><strong>Camera.tsx</strong><dd><code>Fix camera angle constraints for world map view.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/utils/Camera.tsx
<li>Added <code>minAzimuthAngle</code> and <code>maxAzimuthAngle</code> properties to <code>CameraControls</code> <br>component.<br> <li> Set azimuth angle limits based on …

fix: fixed camera angle for worldmap

---

client/src/ui/modules/scenes/MainScene.tsx

Enhancement
___
- Adjusted the properties for `mapCloudsPosition`, `mapCloudsOpacity`, `mapCloudsBounds`, and `mapCloudsVolume` to new values.
- Introduced a `Clouds` component containing two `Cloud` instances to the "map" route in `MainScene.tsx`.
- Each `Cloud` instance has properties such as `concentrate`, `seed`, `speed`, `segments`, `castShadow`, `opacity`, `bounds`, `volume`, and `color`.
___
<tr>
<td>
<details>
<summary><strong>MainScene.tsx</strong><dd><code>Add clouds to WorldMapScene and adjust cloud properties</code>&nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/modules/scenes/MainScene.tsx
<li>Adjusted <code>mapCloudsPosition</code>, …

feat: worldmap clouds

---

client/src/ui/modules/onboarding/Steps.tsx

Bug fix
___
- Added a condition to check if the "Claim Food" quest is already completed before calling `mint_starting_resources` in the onboarding steps.
- Prevented the resource claiming process from being triggered if the quest is already completed, resolving the "resource already claimed" bug.
___
<tr>
<td>
<details>
<summary><strong>Steps.tsx</strong><dd><code>Fix resource already claimed bug in onboarding steps</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/modules/onboarding/Steps.tsx
<li>Added a condition to check if the "Claim Food" quest is already <br>completed before calling <code>mint_starting_resources</code>.<br> …

fix: Fix resource already claimed bug in onboarding

---

client/src/ui/modules/navigation/BottomNavigation.tsx
contracts/manifests/dev/manifest.json
contracts/manifests/dev/manifest.toml
contracts/src/models/combat.cairo
contracts/src/models/realm.cairo
contracts/src/systems/realm/contracts.cairo
contracts/src/systems/realm/tests.cairo

Closes #855
___
Enhancement, Tests
___
- Added realm selection validation in the BottomNavigation component to ensure quests are only available for realm entities.
- Updated contract class hashes and added new DojoModel definitions for `hyperstructure`, `hyperstructure_v_2`, and `tick_move`.
- Added `assert_is_set` function to the `Realm` model to validate if an entity is a realm.
- Enhanced `mint_starting_resources` function to ensure the entity is a realm before minting resources.
- Added new tests for the `mint_starting_resources` function and updated existing realm tests.
___
<tr>
<td>
<details> …

Restrict quests on non-realm entities: client + contract + tests

---

client/src/hooks/store/_mapStore.tsx
client/src/ui/components/worldmap/hexagon/WorldHexagon.tsx

Fixed wrong usage of useMemo.
All setState calls should be placed inside useEffect hooks instead of useMemo.
Wrong usage causing such errors:
___
Bug fix
___
- Replaced incorrect usage of `useMemo` with `useEffect` in two files to ensure state updates are correctly handled.
- Updated built structures setup logic in `_mapStore.tsx`.
- Updated stamina-related calculations in `WorldHexagon.tsx`.
___
<tr>
<td>
<details>
<summary><strong>_mapStore.tsx</strong><dd><code>Replace `useMemo` with `useEffect` for built structures setup</code></dd></summary>
<hr>
client/src/hooks/store/_mapStore.tsx
<li>Replaced <code>useMemo</code> with <code>useEffect</code> for …

fix: wrong usage of useMemo

---

client/src/ui/components/models/armies/WarriorModel.tsx
client/src/ui/components/models/biomes/BeachBiome.tsx
client/src/ui/components/models/biomes/DeciduousForestBiome.tsx
client/src/ui/components/models/biomes/DeepOceanBiome.tsx
client/src/ui/components/models/biomes/DesertBiome.tsx
client/src/ui/components/models/biomes/GrasslandBiome.tsx
client/src/ui/components/models/biomes/OceanBiome.tsx
client/src/ui/components/models/biomes/ScorchedBiome.tsx
client/src/ui/components/models/biomes/ShrublandBiome.tsx
client/src/ui/components/models/biomes/SnowBiome.tsx
client/src/ui/components/models/biomes/SubtropicalDesertBiome.tsx
client/src/ui/components/models/biomes/TaigaBiome.tsx
client/src/ui/components/models/biomes/TemperateDesertBiome.tsx
client/src/ui/components/models/biomes/TemperateRainforestBiome.tsx
client/src/ui/components/models/biomes/TropicalRainforestBiome.tsx
client/src/ui/components/models/biomes/TropicalSeasonalForestBiome.tsx
client/src/ui/components/models/biomes/TundraBiome.tsx
client/src/ui/components/models/buildings/worldmap/Structures.tsx
client/src/ui/components/worldmap/Flags.jsx
client/src/ui/components/worldmap/hexagon/HexLayers.tsx
client/src/ui/components/worldmap/hexagon/HighlightedHexes.tsx

Fix for #861 
Refactor of materials depth sorting
___
___
- Disabled depth write for various materials across multiple biome components to fix depth sorting issues.
- Added `renderOrder` property to `primitive` objects in multiple components to control rendering order.
- Enhanced hexagon grid rendering by adding new materials and handling borders separately.
- Removed `depthTest` property from `hexMaterial` in HighlightedHexes component.
___
</strong></td><td><details><summary>21 files</summary><table>
<tr>
<td>
<details>
<summary><strong>WarriorModel.tsx</strong><dd><code>Set render order for WarriorModel component.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: materials depth test rework #861

---

scripts/contracts.sh

enhancement
___
- Added the `--block-time 3000` option to the `katana` command in the `scripts/contracts.sh` file to enable automatic block mining every 3 seconds.
___
<tr>
<td>
<details>
<summary><strong>contracts.sh</strong><dd><code>Add block time option to katana command</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
scripts/contracts.sh
- Added `--block-time 3000` option to the `katana` command.
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/919/files#diff-424056d6eb01604418b6059c712b6d3390722a5762ff76ff44def87bab506 …

katana: mine block every 3 seconds

---

client/src/ui/components/hints/HintBox.tsx

- Fixes quest claim rewards loading state
- Reverted close quest popup on claim, now the popup only closes when the last quest is claimed
Closes #899
___
___
- Fixed the quest claim rewards loading state by adding a `useEffect` to reset the loading state when the quest is not completed.
- Removed the `togglePopup` call from the `finally` block in `handleClaimResources` to prevent premature popup closure.
- Added logic to close the quest popup only when the last quest is claimed.
- Updated the import alias for `quests` to `QuestOSWindow` for better clarity.
___
<tr>
<td>
<details>
<summary><strong>HintBox.tsx</strong><dd><code>Fix quest …

Fixes quest claim rewards loading state

---

client/src/hooks/helpers/useEntities.tsx
client/src/hooks/helpers/useGuilds.tsx

Closes #947
___
___
- Updated the method for decoding entity names in `useEntities.tsx` to use `shortString.decodeShortString` instead of `hexToAscii`.
- Simplified the `getEntityName` function call in `useGuilds.tsx` by removing unnecessary non-null assertion.
- Improved code readability in the `formatGuilds` function in `useGuilds.tsx`.
___
<tr>
<td>
<details>
<summary><strong>useEntities.tsx</strong><dd><code>Update entity name decoding method to use `shortString`.</code>&nbsp; </dd></summary>
<hr>
client/src/hooks/helpers/useEntities.tsx
<li>Removed <code>hexToAscii</code> import.<br> <li> Added <code>shortString</code> import …

Fix guild names UI

---

client/src/ui/modules/onboarding/Steps.tsx

Closes #924
___
___
- Fixed the "Continue" button being disabled during account creation by correcting the condition that checks if the button should be enabled.
- Replaced hardcoded maximum name length with a constant (`MAX_NAME_LENGTH`) for better maintainability.
- Minor formatting adjustments for better code readability.
___
<tr>
<td>
<details>
<summary><strong>Steps.tsx</strong><dd><code>Fix and enhance naming step in onboarding process</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/modules/onboarding/Steps.tsx
<li>Imported <code>MAX_NAME_LENGTH</code> constant.<br> <li> Replaced …

Fix continue button disabled on acc creation

---

client/src/ui/modules/navigation/TopMiddleNavigation.tsx

Bug fix
___
- Added `setPreviewBuilding` to reset the building preview state when switching from hex to map view.
- Ensured that the building preview is cleared to prevent it from lingering when navigating to the map view.
___
<tr>
<td>
<details>
<summary><strong>TopMiddleNavigation.tsx</strong><dd><code>Fix lingering build preview when switching to map view.</code>&nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/modules/navigation/TopMiddleNavigation.tsx
<li>Added <code>setPreviewBuilding</code> to reset building preview state.<br> <li> Updated map navigation logic to clear building preview when switching <br>to map view.<br>
</details>
</td>
<td><a …

Fixes build preview lingering when going from hex -> map view

---

client/src/hooks/helpers/useStructures.tsx
client/src/ui/components/hyperstructures/StructureCard.tsx
client/src/ui/components/worldmap/armies/useArmyAnimation.tsx
client/src/ui/components/worldmap/hexagon/HexagonInformationPanel.tsx
client/src/ui/components/worldmap/hexagon/utils.tsx

- fixes #965 
- fixes hook warnings/errors when clicking on combat
___
___
- Refactored `useStructuresPosition` to split logic into separate hooks (`useFormattedRealmAtPosition`, `useFormattedStructureAtPosition`, `hasStructuresAtPosition`).
- Updated `StructureCard` and `HexagonInformationPanel` components to use the new hooks.
- Added fallback path logic in `useArmyAnimation` for cases where no path is found.
- Enhanced pathfinding in `findShortestPathBFS` by introducing a stamina-based step limit.
___
<tr>
<td>
<details>
<summary><strong>useStructures.tsx</strong><dd><code>Refactor and enhance structure position hooks</code>&nbsp; …

army travel after raiding + hook error

---

client/src/hooks/helpers/useRealm.tsx
client/src/ui/components/cityview/realm/SettleRealmComponent.tsx

fix #962
checks if next realm id to settle is not on an existing structure, if that's the case, skip that realm and take the next one for that order

Structure bug

---

client/src/ui/components/worldmap/Flags.jsx
client/src/ui/components/worldmap/hexagon/HexLayers.tsx

Fix #970
___
Bug fix
___
- Simplified the `goToHex` function in `HexLayers.tsx` by directly using `e.instanceId` and `e.object`, removing unnecessary intersection checks.
- Removed the redundant `onClick` event handler from a nested `group` element in `Flags.jsx`.
___
<tr>
<td>
<details>
<summary><strong>HexLayers.tsx</strong><dd><code>Simplify `goToHex` function and remove intersection checks</code></dd></summary>
<hr>
client/src/ui/components/worldmap/hexagon/HexLayers.tsx
<li>Simplified the <code>goToHex</code> function by directly using <code>e.instanceId</code> and <br><code>e.object</code>.<br> <li> Removed unnecessary checks for intersections.<br> …

fix: double click bug

---

client/src/ui/components/military/Battle.tsx

small fix
___
Bug fix
___
- Fixed the logic to determine if a pillage was successful by checking if the winner is the attacker.
- Updated the `formatPillageEvent` function to correctly map the winner to the `BattleSide` enum.
- Added the `BattleSide` import to ensure proper type checking and usage.
___
<tr>
<td>
<details>
<summary><strong>Battle.tsx</strong><dd><code>Fix pillage success determination logic in Battle component</code></dd></summary>
<hr>
client/src/ui/components/military/Battle.tsx
<li>Added <code>BattleSide</code> import from <code>@bibliothecadao/eternum</code>.<br> <li> Updated <code>isPillageSucess</code> function to check if the winner is …

fix pillage successful bug

---

client/src/ui/components/trading/MarketOrderPanel.tsx

Bug fix
___
- Fixed the conditional rendering logic for the market order buttons in `MarketOrderPanel.tsx`.
- Ensured that the correct button (buy/sell or cancel) displays based on whether the user is the order creator and if they have sufficient funds.
___
<tr>
<td>
<details>
<summary><strong>MarketOrderPanel.tsx</strong><dd><code>Fix conditional rendering for market order buttons</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/ui/components/trading/MarketOrderPanel.tsx
<li>Fixed the conditional rendering logic for the market order buttons.<br> <li> Ensured the correct button displays based on user role and order …

fix market button

---

client/src/ui/modules/navigation/TopMiddleNavigation.tsx

Bug fix
___
- Fixed the import order for `motion` from `framer-motion` to resolve potential issues.
- Added `realmEntityId` as a dependency in the `useMemo` hook to ensure proper reactivity when sorting player structures.
___
<tr>
<td>
<details>
<summary><strong>TopMiddleNavigation.tsx</strong><dd><code>Fix import order and update dependencies in useMemo hook</code>&nbsp; </dd></summary>
<hr>
client/src/ui/modules/navigation/TopMiddleNavigation.tsx
<li>Fixed import order for <code>motion</code> from <code>framer-motion</code>.<br> <li> Added <code>realmEntityId</code> as a dependency in the <code>useMemo</code> hook for sorting <br>player structures.<br> …

fix: bug in top middle navigation realms

---

.github/workflows/lint.yml
.prettierignore
client/src/index.css
client/src/ui/modules/military/battle-view/BattleProgressBar.tsx

enhancement, configuration changes
___
- Updated the Prettier command in the CI configuration file to use `pnpm run prettier-check` instead of `pnpm run prettier --check .`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>lint.yml</strong><dd><code>Update Prettier command in CI configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/lint.yml
<li>Changed the Prettier command from <code>pnpm run prettier --check .</code> to <code>pnpm </code><br><code>run prettier-check</code>.<br>
</details>
</td>
<td><a …

Change 'prettier' call from write to check

---

.github/workflows/test.yml

configuration changes
___
- Updated the Dojo version in the CI workflow from `v0.7.0-alpha.5` to `v0.7.2`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>test.yml</strong><dd><code>Update Dojo version in CI workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/test.yml
<li>Updated the Dojo version in the CI workflow from <code>v0.7.0-alpha.5</code> to <br><code>v0.7.2</code>.<br>
</details>
</td>
<td><a href="https://github.com/BibliothecaDAO/eternum/pull/1037/files#diff-faff1af3d8ff408964a57b2 …

Bump dojo version in CI

---

client/src/hooks/helpers/useHexPosition.tsx
client/src/ui/elements/CircleButton.tsx
client/src/ui/modules/navigation/LeftNavigationModule.tsx
client/src/ui/modules/navigation/RightNavigationModule.tsx

Also disable contruction + trade menu
Closes #944
___
___
- Simplified the logic to set `realmEntityId` in the `useHexPosition` hook by removing redundant checks.
- Disabled notifications for `CircleButton` when the button is disabled.
- Added checks to disable construction, trade, and resource buttons in navigation modules when the realm is not owned by the user.
___
<tr>
<td>
<details>
<summary><strong>useHexPosition.tsx</strong><dd><code>Simplify `realmEntityId` setting logic in `useHexPosition` hook</code></dd></summary>
<hr>
client/src/hooks/helpers/useHexPosition.tsx
<li>Removed <code>STARTING_ENTITY_ID</code> import.<br> <li> …

set realmEntityId when clicking on structure not owned by us.

---

client/src/ui/components/construction/SelectPreviewBuilding.tsx

Enhancement
___
- Added a new state `quests` from `useQuestStore` to track quests.
- Implemented `isQuestClaimedByName` function to determine if a quest is claimed.
- Modified the visibility conditions for `BuildingCard` components to depend on the quest completion status instead of the selected quest.
___
<tr>
<td>
<details>
<summary><strong>SelectPreviewBuilding.tsx</strong><dd><code>Update building card visibility based on quest completion</code></dd></summary>
<hr>
client/src/ui/components/construction/SelectPreviewBuilding.tsx
<li>Added <code>quests</code> state from <code>useQuestStore</code>.<br> <li> Introduced <code>isQuestClaimedByName</code> …

Show building cards depending on quests cleared

---

sdk/packages/eternum/src/constants/resources.ts

Enhancement
___
- Adjusted the indentation for resource tiers in the `getLevelingCost` function for better readability.
- Updated quest rewards for various quest types from `ResourcesIds.Wheat` to `ResourcesIds.Earthenshard` and increased the amount from 1 to 5.
___
<tr>
<td>
<details>
<summary><strong>resources.ts</strong><dd><code>Update quest rewards and adjust resource tier indentation</code></dd></summary>
<hr>
sdk/packages/eternum/src/constants/resources.ts
<li>Adjusted indentation for leveling cost resource tiers.<br> <li> Updated quest rewards from <code>ResourcesIds.Wheat</code> to <br><code>ResourcesIds.Earthenshard</code> and increased the …

update reward to fragments

---

contracts/manifests/dev/manifest.json
contracts/manifests/dev/manifest.toml
contracts/src/systems/map/contracts.cairo

Bug fix
___
- Updated `class_hash` and `original_class_hash` values for `DojoContract` in both `manifest.json` and `manifest.toml`.
- Fixed ownership validation in `map_systems` contract by removing the realm ownership check and adding a caller ownership check.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update class hashes for DojoContract in manifest.json</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
contracts/manifests/dev/manifest.json
<li>Updated <code>class_hash</code> and <code>original_class_hash</code> values for <code>DojoContract</code>.<br>
</details>
</td>
<td><a …

Fix exploring w/ army owned by structure that isnt a realm

---

contracts/manifests/dev/manifest.json
contracts/manifests/dev/manifest.toml
contracts/src/systems/combat/contracts.cairo

- disallow battle join after battle ends
- if `battle_start` is called against an army that is still in battle and the battle has ended, the army is automatically forced to leave the old battle so that it can join the new one
___
___
- Added logic to disallow armies from joining a battle after it has ended.
- Implemented updates to defending army's battle status to remove it from ended battles.
- Added health invariant checks for both attacking and defending armies to ensure they are at full health before starting a battle.
- Ensured both armies are alive and in the same location before initiating a battle.
- Added a panic to handle cases where a battle has already ended.
___
<table><thead><tr><th></th><th align="left">Relevant …

contracts: disallow join after battle ends

---

client/src/hooks/helpers/useQuests.tsx
client/src/ui/components/quest/QuestList.tsx
client/src/ui/modules/navigation/LeftNavigationModule.tsx

___
- Refactored the `createQuest` function in `useQuests.tsx` to use `useMemo` directly, simplifying the code and improving performance.
- Simplified the status determination logic for various quests in `useQuests.tsx`.
- Fixed the filter condition for `unclaimedQuests` in `QuestList.tsx` to correctly exclude claimed quests.
- Added `questClaimStatus` to the dependency array of `useMemo` in `LeftNavigationModule.tsx` to ensure proper memoization.
___
<tr>
<td>
<details>
<summary><strong>useQuests.tsx</strong><dd><code>Refactor quest creation and status logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix small ui bugs

---

client/src/dojo/setup.ts

Nasr helped us by giving us this quick fix. We can remove this when we switch to dojo-1.0-alpha.5
___
Bug fix
___
- Reordered imports in `client/src/dojo/setup.ts` for better organization.
- Fixed the subscriptions setup by modifying the `getSyncEntities` call to include wildcard pattern matching.
- Added a configuration object to the `getSyncEntities` function to support pattern matching with `VariableLen`.
___
<tr>
<td>
<details>
<summary><strong>setup.ts</strong><dd><code>Fix wildcard pattern matching in subscriptions setup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/dojo/setup.ts
<li>Reordered imports for better …

fix: subscriptions with wildcard pattern matching

---

client/src/three/systems/SystemManager.ts

Bug fix
___
- Imported `EternumGlobalConfig` to access global configuration values.
- Added logic to filter out armies that are currently in battle.
- Added logic to filter out armies that are dead by checking their health against `EternumGlobalConfig.troop.healthPrecision`.
___
<tr>
<td>
<details>
<summary><strong>SystemManager.ts</strong><dd><code>Add filtering for armies in battle and dead armies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/systems/SystemManager.ts
<li>Imported <code>EternumGlobalConfig</code> from <code>@bibliothecadao/eternum</code>.<br> <li> Added filtering logic for armies in battle and …

fixes #1160

---

client/src/three/scenes/Worldmap.ts
client/src/ui/containers/TopLeftContainer.tsx

#1163 fix
___
___
- Fixed and enhanced hex cache management in the `WorldmapScene` to ensure hexes are correctly added and removed based on chunk visibility.
- Added conditional checks to manage hexes within the chunk and updated the interactive hex manager accordingly.
- Cached matrices for chunks and removed cached matrices for non-visible chunks to optimize performance.
- Enabled pointer events for the `TopLeftContainer` by adding the `pointer-events-auto` class.
___
<tr>
<td>
<details>
<summary><strong>Worldmap.ts</strong><dd><code>Fix and enhance hex cache management in Worldmap scene</code>&nbsp; &nbsp; &nbsp; </dd></summary> …

fix: explored hex cache bug

---

client/src/three/components/InputManager.ts

Closes #1158
___
Bug fix
___
- Fixed an issue where a click event was firing after a drag operation.
- Removed the `mouseup` event listener and added drag detection logic within the `handleMouseDown` method.
- Introduced an `isDragged` flag to track whether a drag operation has occurred.
___
<tr>
<td>
<details>
<summary><strong>InputManager.ts</strong><dd><code>Fix click event firing after drag operation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/components/InputManager.ts
<li>Removed <code>mouseup</code> event listener.<br> <li> Added <code>isDragged</code> …

fix click firing after drag

---

client/src/three/scenes/HexagonScene.ts
client/src/three/scenes/Hexception.ts
client/src/three/scenes/Worldmap.ts

enhancement, bug fix
___
- Added state management to `HexagonScene` using `useUIStore`.
- Fixed issue in `HexceptionScene` by setting `previewBuilding` to null in `clearBuildingMode`.
- Removed redundant state management code in `WorldmapScene`.
___
<tr>
<td>
<details>
<summary><strong>HexagonScene.ts</strong><dd><code>Add state management to HexagonScene using useUIStore</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/scenes/HexagonScene.ts
<li>Imported <code>useUIStore</code> and <code>AppStore</code>.<br> <li> Added <code>state</code> property to <code>HexagonScene</code> class.<br> <li> Initialized <code>state</code> in the …

set preview building zustand state to null + add state to HexagonScene

---

client/src/three/scenes/constants.ts

bug fix
___
- Fixed an issue where `BuildingType.None` did not have a valid model path, causing model loading problems.
- Updated the `BuildingType.None` model path to `/models/buildings/farm.glb` in `buildingModelPaths`.
___
<tr>
<td>
<details>
<summary><strong>constants.ts</strong><dd><code>Fix model loading for `BuildingType.None` by adding valid path</code></dd></summary>
<hr>
client/src/three/scenes/constants.ts
<li>Updated the <code>BuildingType.None</code> model path to a valid model file.<br> <li> Changed the path from an empty string to <code>/models/buildings/farm.glb</code>.<br>
</details>
</td>
<td><a …

Add model to BuildingType.none to fix model loading

---

client/src/three/components/ArmyManager.ts

___
- Added a new `isMine` property to the `armies` map to track whether an army belongs to the player.
- Updated the `getClickedArmyId` method to prevent the selection of enemy armies.
- Modified the `addArmy` and `moveArmy` methods to incorporate the new `isMine` property, ensuring proper handling of army ownership.
___
<tr>
<td>
<details>
<summary><strong>ArmyManager.ts</strong><dd><code>Prevent selection of enemy armies and track ownership</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
client/src/three/components/ArmyManager.ts
<li>Added <code>isMine</code> property to the <code>armies</code> map to track ownership.<br> …

prevent select enemy army

---

contracts/src/models/combat.cairo

resolves #1384 
- previously battle duration was always set to at least 1 second even if one army was dead. now if any army is dead, duration is 0

contracts: fix battle duration bug

---

client/src/ui/components/bank/ResourceBar.tsx

Cannot test it since the AMM is not initialised locally and I didnt find how but quite confident in the fix.
Actually in my browser I have numbers displayed such as every thousands is space separated such as 9 999 for. 9999, parseInt("9 999") is 9 which was my issue
Closes #1667

🐛 Fix AMM input issue

---

client/src/ui/components/hyperstructures/CoOwners.tsx
client/src/ui/components/hyperstructures/Leaderboard.tsx
client/src/ui/components/worldmap/leaderboard/PlayersLeaderboard.tsx

Remove order icon for player address info

---

client/src/ui/components/trading/MarketOrderPanel.tsx

cap buy and sell orders by resource and lords balance

---

client/src/dojo/contractComponents.ts
contracts/src/models/combat.cairo
contracts/src/models/config.cairo
contracts/src/systems/combat/tests/battle_leave_test.cairo
contracts/src/systems/combat/tests/battle_pillage_test.cairo
contracts/src/systems/map/tests.cairo
contracts/src/utils/math.cairo
contracts/src/utils/testing/config.cairo
sdk/packages/eternum/src/config/index.ts
sdk/packages/eternum/src/constants/global.ts
sdk/packages/eternum/src/provider/index.ts
sdk/packages/eternum/src/types/common.ts
sdk/packages/eternum/src/types/provider.ts

make the battle time calculations more sane
- there's now a config to increase and reduce battle time more directly through `battle_time_scale`
- battle time goes up with the number of troops in battle and there is no upper time limit
- the smaller army now loses troops quicker than the bigger army

update battle time calculations

---

contracts/src/models/config.cairo
contracts/src/models/resources.cairo

resolves #1806 
- fix division error when calculating max storehouse capacity
- only limit resource storage capacity for realms

storehouse capacity rounding error fix

---

client/src/dojo/modelManager/TileManager.ts
client/src/three/scenes/Worldmap.ts
client/src/ui/components/hyperstructures/StructureCard.tsx
client/src/ui/components/structures/worldmap/StructureCard.tsx
client/src/ui/elements/KeyBoardKey.tsx
client/src/ui/modules/navigation/LeftNavigationModule.tsx

Fixes #1897
- remove double click to go inside hex view
- click two times on same hex shows entity details
- press "E" shows entity details

[client] improve entity details show/hide

---

docs/pages/mechanics/military/units.mdx

```diff
- Armies have limited storage and cannot move if storage is full, stamina is depleted or there is not enough food at the
home realm
+++- Armies can't move if their stamina is depleted or there is not enough food at the home realm
+++- Armies have limited storage and cannot explore if storage is full, but they can retrace back to the home realm to unload
```

clarify army movement
